### ISSUE TITLE
Slightly inaccurate voltage

### ISSUE THREAD

**Issue by end360** [openhardwaremonitor/openhardwaremonitor#1028]
GPU: AMD R7 200 series
Problem: http://imgur.com/a/vlVWi

**Comment by colorburst** [comment]
Please post the report for us to look at, it might shed light on the issue.

**Comment by end360** [comment]
I will as soon as I get home ( about 6 hours )

**Comment by DarthDestroyer** [comment]
I think i had seen another Issue like that...
#825 and a old one #447

825 talks about Voltage, but maybe it is related?!

A Report would help here, yes!

**Comment by end360** [comment]
[OpenHardwareMonitor.Report.txt](https://github.com/openhardwaremonitor/openhardwaremonitor/files/1326086/OpenHardwareMonitor.Report.txt)

**Comment by DarthDestroyer** [comment]
could you try the latest version, too?

http://openhardwaremonitor.org/files/openhardwaremonitor-v0.8.0.3-alpha.zip

**Comment by end360** [comment]
Still the same: 
[OpenHardwareMonitor.Report2.txt](https://github.com/openhardwaremonitor/openhardwaremonitor/files/1326148/OpenHardwareMonitor.Report2.txt)
