### ISSUE TITLE
Reading AMD's Ryzen Tcl/TDie

### ISSUE THREAD

**Issue by BrianLima** [openhardwaremonitor/openhardwaremonitor#1037]
I'm using the fork by myfreweb and dernerv and it does support Ryzen motherboards, their fan curve support is really cool too, but i'm getting mixed results, HWiNFO reports higher temperatures than OHM because of Ryzen's Tcl/Tdie readings, would it be possible to have it on OHM?

**Comment by Kraust** [comment]
![image](https://user-images.githubusercontent.com/6548135/32705264-1440be9c-c7e0-11e7-8169-8004df007007.png)


Currently working on a solution for this. Stay Tuned. Took the k10temp implementation and ported it to OpenHardwareMonitor.

**Comment by BrianLima** [comment]
I think that the 20c offset problem for X series cpu's is gone, they removed it on a bios update if i remember correctly.
 I own a 1700 too, thanks for the update! Just hope they comeback to merge all the changes the community made or that another fork takes its place.

**Comment by FireFrenzy** [comment]
My brand new 1950x has the offset between Tdie and Tcl... 

And thats on a week old motherboard with the latest bios on it (gigabyte gaming 7) where there is also no OHM support...

**Comment by moellerm** [comment]
This should be fixed in OHM version 0.9.0 and later.
