### ISSUE TITLE
OpenHardwareMonitorReport .net4

### ISSUE THREAD

**Issue by FedyaLutkovski** [openhardwaremonitor/openhardwaremonitor#1054]
HI! Could you recompile OpenHardwareMonitorReport for working with .net4?

**Comment by DarthDestroyer** [comment]
Feel free, to do it by yourself!

There is atm no need to... 
Why are you thinking about that?

**Comment by FedyaLutkovski** [comment]
I'm very sorry, but I can not find the source files OpenHardwareMonitorReport
