### ISSUE TITLE
Intel Celeron 430 temperatyre not supported 

### ISSUE THREAD

**Issue by FedyaLutkovski** [openhardwaremonitor/openhardwaremonitor#1055]
The temperature display is not supported on this old processor. Can I do something about this, or is this equipment not going to be supported?

**Comment by DarthDestroyer** [comment]
Without a Report, it is impossible to say!

Could you provide one?

**Comment by FedyaLutkovski** [comment]
Oh sure

Open Hardware Monitor Report

--------------------------------------------------------------------------------

Version: 0.8.0.3

--------------------------------------------------------------------------------

Common Language Runtime: 2.0.50727.8762
Operating System: Microsoft Windows NT 6.1.7601 Service Pack 1
Process Type: 32-Bit

--------------------------------------------------------------------------------

Sensors

|
+- ASUS P5KPL-AM (/mainboard)
|  |
|  +- Winbond W83627DHG (/lpc/w83627dhg)
|  |  +- CPU VCore      :     1.32     1.32     1.32 (/lpc/w83627dhg/voltage/0)
|  |  +- Voltage #2     :     1.84     1.84     1.84 (/lpc/w83627dhg/voltage/1)
|  |  +- AVCC           :    3.248    3.248    3.248 (/lpc/w83627dhg/voltage/2)
|  |  +- 3VCC           :    3.248    3.248    3.248 (/lpc/w83627dhg/voltage/3)
|  |  +- Voltage #5     :    1.256    1.256    1.256 (/lpc/w83627dhg/voltage/4)
|  |  +- Voltage #6     :    1.592    1.592    1.592 (/lpc/w83627dhg/voltage/5)
|  |  +- Voltage #7     :    1.224    1.224    1.224 (/lpc/w83627dhg/voltage/6)
|  |  +- 3VSB           :    3.248    3.248    3.248 (/lpc/w83627dhg/voltage/7)
|  |  +- Auxiliary      :       27       27       27 (/lpc/w83627dhg/temperature/1)
|  |  +- System         :       28       28       28 (/lpc/w83627dhg/temperature/2)
|  |  +- CPU Fan        :  1997.04  1997.04  1997.04 (/lpc/w83627dhg/fan/1)
|  |  +- Auxiliary Fan  :  1767.02  1767.02  1767.02 (/lpc/w83627dhg/fan/2)
|
+- Intel Celeron 430 (/intelcpu/0)
|  +- CPU Core       :  93.9655  93.9655      100 (/intelcpu/0/load/1)
|
+- Generic Memory (/ram)
|  +- Memory         :  53.8497  53.8497  53.8497 (/ram/load/0)
|  +- Used Memory    : 0.533333 0.533333 0.533333 (/ram/data/0)
|  +- Available Memory : 0.457077 0.457077 0.457077 (/ram/data/1)
|
+- ST380815AS (/hdd/0)
|  +- Temperature    :       34       34       34 (/hdd/0/temperature/0)
|  +- Used Space     :  80.3421  80.3421  80.3421 (/hdd/0/load/0)

--------------------------------------------------------------------------------

Parameters

|
+- ASUS P5KPL-AM (/mainboard)
|  |
|  +- Winbond W83627DHG (/lpc/w83627dhg)
|  |  |
|  |  +- CPU VCore (/lpc/w83627dhg/voltage/0)
|  |  |  +- Ri [k?] : 0 : 0
|  |  |  +- Rf [k?] : 1 : 1
|  |  |  +- Vf [V] : 0 : 0
|  |  |
|  |  +- Voltage #2 (/lpc/w83627dhg/voltage/1)
|  |  |  +- Ri [k?] : 0 : 0
|  |  |  +- Rf [k?] : 1 : 1
|  |  |  +- Vf [V] : 0 : 0
|  |  |
|  |  +- AVCC (/lpc/w83627dhg/voltage/2)
|  |  |  +- Ri [k?] : 34 : 34
|  |  |  +- Rf [k?] : 34 : 34
|  |  |  +- Vf [V] : 0 : 0
|  |  |
|  |  +- 3VCC (/lpc/w83627dhg/voltage/3)
|  |  |  +- Ri [k?] : 34 : 34
|  |  |  +- Rf [k?] : 34 : 34
|  |  |  +- Vf [V] : 0 : 0
|  |  |
|  |  +- Voltage #5 (/lpc/w83627dhg/voltage/4)
|  |  |  +- Ri [k?] : 0 : 0
|  |  |  +- Rf [k?] : 1 : 1
|  |  |  +- Vf [V] : 0 : 0
|  |  |
|  |  +- Voltage #6 (/lpc/w83627dhg/voltage/5)
|  |  |  +- Ri [k?] : 0 : 0
|  |  |  +- Rf [k?] : 1 : 1
|  |  |  +- Vf [V] : 0 : 0
|  |  |
|  |  +- Voltage #7 (/lpc/w83627dhg/voltage/6)
|  |  |  +- Ri [k?] : 0 : 0
|  |  |  +- Rf [k?] : 1 : 1
|  |  |  +- Vf [V] : 0 : 0
|  |  |
|  |  +- 3VSB (/lpc/w83627dhg/voltage/7)
|  |  |  +- Ri [k?] : 34 : 34
|  |  |  +- Rf [k?] : 34 : 34
|  |  |  +- Vf [V] : 0 : 0
|  |  |
|  |  +- Auxiliary (/lpc/w83627dhg/temperature/1)
|  |  |  +- Offset [°C] : 0 : 0
|  |  |
|  |  +- System (/lpc/w83627dhg/temperature/2)
|  |  |  +- Offset [°C] : 0 : 0
|
+- Intel Celeron 430 (/intelcpu/0)
|
+- Generic Memory (/ram)
|
+- ST380815AS (/hdd/0)
|  |
|  +- Temperature (/hdd/0/temperature/0)
|  |  +- Offset [°C] : 0 : 0

--------------------------------------------------------------------------------

Mainboard

SMBIOS Version: 2.5

BIOS Vendor: American Megatrends Inc.
BIOS Version: 0309

System Manufacturer: System manufacturer
System Name: System Product Name
System Version: System Version

Mainboard Manufacturer: ASUSTeK Computer INC.
Mainboard Name: P5KPL-AM
Mainboard Version: x.xx

Processor Manufacturer: Intel
Processor Version: Intel(R) Celeron(R) CPU 430 @ 1.80GHz
Processor Core Count: 0
Processor Core Enabled: 0
Processor Thread Count: 0
Processor External Clock: 200 Mhz

Memory Device [0] Manufacturer: Manufacturer0
Memory Device [0] Part Number: PartNum0
Memory Device [0] Device Locator: DIMM A1
Memory Device [0] Bank Locator: BANK0
Memory Device [0] Speed: 800 MHz

Memory Device [1] Manufacturer: Manufacturer1
Memory Device [1] Part Number: PartNum1
Memory Device [1] Device Locator: DIMM B1
Memory Device [1] Bank Locator: BANK1
Memory Device [1] Speed: 0 MHz

SMBIOS Table

 ABgAAAECAPADD5Dei38BAAAAMwUIDP//QW1lcmljYW4gTWVnYXRyZW5kcyBJbmMu
 ADAzMDkgICAAMDUvMjAvMjAwOAAAARsBAAECAwQASLtxzGvdEb3tACIVmOA3BgUG
 U3lzdGVtIG1hbnVmYWN0dXJlcgBTeXN0ZW0gUHJvZHVjdCBOYW1lAFN5c3RlbSBW
 ZXJzaW9uAFN5c3RlbSBTZXJpYWwgTnVtYmVyAFRvIEJlIEZpbGxlZCBCeSBPLkUu
 TS4AVG8gQmUgRmlsbGVkIEJ5IE8uRS5NLgAAAg8CAAECAwQFCQYDAAoAQVNVU1Rl
 SyBDb21wdXRlciBJTkMuAFA1S1BMLUFNAHgueHgATVMxQzg4QjgxTTA0MDg4AFRv
 IEJlIEZpbGxlZCBCeSBPLkUuTS4AVG8gQmUgRmlsbGVkIEJ5IE8uRS5NLgAAAxUD
 AAEDAgMEAwMDAwEAAAAAAQAAQ2hhc3NpcyBNYW51ZmFjdHVyZQBDaGFzc2lzIFZl
 cnNpb24AQ2hhc3NpcyBTZXJpYWwgTnVtYmVyAEFzc2V0LTEyMzQ1Njc4OTAAAAQo
 BAABAwECYQYBAP/7668DjcgA2A4IB0EVBQAGAAcABAUGAAAAAABTb2NrZXQgNzc1
 AEludGVsICAgICAgICAgICAgAEludGVsKFIpIENlbGVyb24oUikgQ1BVIDQzMCBA
 IDEuODBHSHogICAgICAgICAgICAgICAAVG8gQmUgRmlsbGVkIEJ5IE8uRS5NLgBU
 byBCZSBGaWxsZWQgQnkgTy5FLk0uAFRvIEJlIEZpbGxlZCBCeSBPLkUuTS4AAAcT
 BQABgAEgACAAAQABAAAEBAFMMS1DYWNoZQAABxMGAAGBAQACAAIBAAEAAAUFAUwy
 LUNhY2hlAAAHEwcAAQIDAAAAAAIAAgAAAgICTDMtQ2FjaGUAAAYMCAABARkABYqK
 AERJTU0gQTEAAAYMCQABIwAABX9/AERJTU0gQjEAAAgJCgABAAIPDlBTLzIgTW91
 c2UAUFMvMiBNb3VzZQAACAkLAAEAAg8NS2V5Ym9hcmQAUFMvMiBLZXlib2FyZAAA
 CAkMAAEAAhIQVVNCMQBVU0IxAAAICQ0AAQACEhBVU0IyAFVTQjIAAAgJDgABAAIS
 EFVTQjMAVVNCMwAACAkPAAEAAhIQVVNCNABVU0I0AAAICRAAAQACEhBVU0I1AFVT
 QjUAAAgJEQABAAISEFVTQjYAVVNCNgAACAkSAAEAAhIQVVNCNwBVU0I3AAAICRMA
 AQACEhBVU0I4AFVTQjgAAAgJFAABAAIICUNPTSAxAENPTSAxAAAICRUAAQACHx1B
 dWRpb19MaW5lIEluAEF1ZGlvX0xpbmUgSW4AAAgJFgABAAIfHUF1ZGlvX0xpbmUg
 T3V0AEF1ZGlvX0xpbmUgT3V0AAAICRcAAQACHx1BdWRpb19NaWMgSW4AQXVkaW9f
 TWljIEluAAAICRgAAQACHx1BdWRpb19DZW50ZXIvTEZFAEF1ZGlvX0NlbnRlci9M
 RkUAAAgJGQABAAIfHUF1ZGlvX1N1cnJvdW5kIE9VVABBdWRpb19TdXJyb3VuZCBP
 VVQAAAgJGgABAAIfHUF1ZGlvX1N1cnJvdW5kIEJhY2sAQXVkaW9fU3Vycm91bmQg
 QmFjawAACAkbAAEAAhwdU1BESUZfT1VUAFNQRElGX09VVAAACAkcAAEAAgsfR2JF
 IExBTiAxAEdiRSBMQU4gMQAACAkdAAEAAgQFTFBUAExQVCAxAAAICR4AARYAAP9T
 Ql9TQVRBMQAACAkfAAEWAAD/U0JfU0FUQTIAAAgJIAABFgAA/1NCX1NBVEEzAAAI
 CSEAARYAAP9TQl9TQVRBNAAACAkiAAH/AAD/Q0hBX0ZBTjEAAAgJIwABHAAAHUNE
 AAAICSQAARwAAB1GUF9BVURJTwAACAklAAEXAAD/RkxPUFBZAAAICSYAAf8AAP9D
 UFVfRkFOAAAICScAAf8AAP9QV1JfRkFOAAAICSgAAf8AAP9TcGVha2VyAAAJDSkA
 AaUNAwMBAAwBUENJRVgxNgAACQ0qAAEGBQMDAgAMAVBDSV8xAAAJDSsAAQYFAwMD
 AAwBUENJXzIAAAkNLAABpQgDAwQADAFQQ0lFWDFfMQAACgYtAIUBIE9uYm9hcmQg
 RXRoZXJuZXQAAAsFLgAEMDAyMjE1OThFMDM3AFRvIEJlIEZpbGxlZCBCeSBPLkUu
 TS4AVG8gQmUgRmlsbGVkIEJ5IE8uRS5NLgBUbyBCZSBGaWxsZWQgQnkgTy5FLk0u
 AAANFi8AAf8AAAAAAAAAAAAAAAAAAAABZW58VVN8aXNvODg1OS0xAAAPIzAABAAA
 AAIAAgAAAAAAagRsBAAGAv///////////////wAAEA8xAAMDAwAAQAD+/wIAAAAT
 DzIAAAAAAP//DwAxAAQAABEbMwAxAP7/QABAAAAECQABAhOAACADAwQFBkRJTU0g
 QTEAQkFOSzAATWFudWZhY3R1cmVyMABTZXJOdW0wAEFzc2V0VGFnTnVtMABQYXJ0
 TnVtMAAAFBM0AAAAAAD//w8AMwAyAAEAAQAAERs1ADEA/v//////AAAJAAECAgQA
 AAADBAUGRElNTSBCMQBCQU5LMQBNYW51ZmFjdHVyZXIxAFNlck51bTEAQXNzZXRU
 YWdOdW0xAFBhcnROdW0xAAAUEzYAAAAAAAAAAAA1ADIAAQABAAAgFDcAAAAAAAAA
 AAAAAAAAAAAAAAAAfwQ4AAAA

--------------------------------------------------------------------------------

LPC W836XX

Chip ID: 0xA020
Chip revision: 0x23
Base Adress: 0x0290

Hardware Monitor Registers

      00 01 02 03 04 05 06 07 08 09 0A 0B 0C 0D 0E 0F

 00   04 FF 04 FF 01 00 3D 10 01 4B 01 01 3C 3C 0A 05
 10   04 FF 10 00 00 01 01 3C 43 17 00 00 FF FF FF CF
 20   A5 E6 CB CB 9D C7 99 1C FF A9 BF DA 00 00 A3 01
 30   10 80 0E 0C 40 00 29 21 82 02 12 0A 00 40 00 FF
 40   03 00 00 FF FF FF 07 B5 2D 02 00 84 90 95 00 A3
 50   FF FF 00 FF FF FF 00 80 C1 EF FF FF 19 24 00 05
 60   04 7F 40 00 01 01 3C FF 12 FF 01 FF FF FF FF FF
 70   FF FF FF FF FF FF FF FF FF FF FF FF FF FF FF FF
Bank 1
 50   1C 00 00 4B 00 50 05 FE FF FF FF FF FF FF FF FF
Bank 2
 50   1B 00 00 4B 00 50 19 00 FF FF FF FF FF FF FF FF
Bank 3
 50   03 03 07 07 01 07 03 07 00 07 00 00 17 06 00 00
Bank 4
 50   00 13 FF 00 00 1F 00 0B 4C DE 0D B3 09 5D 20 7F
Bank 5
 50   CB 21 0B FF 20 88 00 24 15 01 00 00 88 00 00 00
Bank 6
 50   FF FF FF FF FF FF FF FF FF FF FF FF FF FF FF FF
Bank 7
 50   63 C0 00 00 00 A2 BF 77 80 64 08 68 29 0F 00 00
Bank 8
 50   FF FF 00 FF FF FF 00 80 C1 EF FF FF 19 24 00 05
Bank 9
 50   1C 00 00 4B 00 50 05 FE FF FF FF FF FF FF FF FF
Bank 10
 50   1B 00 00 4B 00 50 19 00 FF FF FF FF FF FF FF FF
Bank 11
 50   03 03 07 07 01 07 03 07 00 07 00 00 17 06 00 00
Bank 12
 50   00 13 FF 00 00 1F 00 0B 4C DE 0D B3 09 5D 20 7F
Bank 13
 50   CB 21 0B FF 20 88 00 24 15 01 00 00 88 00 00 00
Bank 14
 50   FF FF FF FF FF FF FF FF FF FF FF FF FF FF FF FF
Bank 15
 50   63 C0 00 00 00 A2 BF 77 80 64 08 68 29 0F 00 00

--------------------------------------------------------------------------------

CPUID

Processor 0

Processor Vendor: Intel
Processor Brand: Intel(R) Celeron(R) CPU          430  @ 1.80GHz
Family: 0x6
Model: 0x16
Stepping: 0x1

CPUID Return Values

 CPU Thread: 0
 APIC ID: 0
 Processor ID: 0
 Core ID: 0
 Thread ID: 0

 Function  EAX       EBX       ECX       EDX
 00000000  0000000A  756E6547  6C65746E  49656E69
 00000001  00010661  00010800  0000E31D  AFEBFBFF
 00000002  05B0B101  005657F0  00000000  2CB4307F
 00000003  00000000  00000000  00000000  00000000
 00000004  00000121  01C0003F  0000003F  00000001
 00000005  00000040  00000040  00000003  00000220
 00000006  00000001  00000002  00000001  00000000
 00000007  00000000  00000000  00000000  00000000
 00000008  00000400  00000000  00000000  00000000
 00000009  00000000  00000000  00000000  00000000
 0000000A  07280202  00000000  00000000  00000000
 80000000  80000008  00000000  00000000  00000000
 80000001  00000000  00000000  00000001  20100000
 80000002  65746E49  2952286C  6C654320  6E6F7265
 80000003  20295228  20555043  20202020  20202020
 80000004  30333420  20402020  30382E31  007A4847
 80000005  00000000  00000000  00000000  00000000
 80000006  00000000  00000000  02002040  00000000
 80000007  00000000  00000000  00000000  00000000
 80000008  00003024  00000000  00000000  00000000

--------------------------------------------------------------------------------

Intel CPU

Name: Intel Celeron 430
Number of Cores: 1
Threads per Core: 1
Timer Frequency: 1.772373 MHz
Time Stamp Counter: Not Invariant
Estimated Time Stamp Counter Frequency: 1815.21 MHz
Estimated Time Stamp Counter Frequency Error: 0.40967 Mhz
Time Stamp Counter Frequency: 1815.21 MHz

MSR Core #1

 MSR       EDX       EAX
 000000CE  00120926  7F7F060B
 00000198  09260926  06000926
 0000019C  00000000  88330000
 000001A2  00000000  00000E00

Microarchitecture: Unknown
Time Stamp Counter Multiplier: 0

--------------------------------------------------------------------------------

AMD Display Library

Status: -1

--------------------------------------------------------------------------------

GenericHarddisk

Drive name: ST380815AS
Firmware version: 4.AAB

 ID Description                        Raw Value    Worst Value Thres Physical
 01 Read Error Rate                    000000000000 253   100   6     -
 03 Spin-Up Time                       000000000000 97    97    0     -
 04 Start/Stop Count                   4E0900000000 98    98    20    2382
 05 Reallocated Sectors Count          000000000000 100   100   36    -
 07 Seek Error Rate                    A2CFBE270000 60    87    30    -
 09 Power-On Hours (POH)               E85F00000000 72    72    0     24552
 0A Spin Retry Count                   000000000000 100   100   97    -
 0C Power Cycle Count                  5D0900000000 98    98    20    2397
 BB Reported Uncorrectable Errors      000000000000 100   100   0     0
 BD High Fly Writes                    000000000000 100   100   0     -
 BE Temperature Difference from 100    220017230000 54    66    45    34
 C2 Temperature                        220000001100 46    34    0     34
 C3 Hardware ECC Recovered             E8EE9C0D0000 69    74    0     -
 C5 Current Pending Sector Count       000000000000 100   100   0     -
 C6 Uncorrectable Sector Count         000000000000 100   100   0     -
 C7 UltraDMA CRC Error Count           000000000000 200   200   0     -
 C8 Write Error Rate                   000000000000 253   100   0     -
 CA Data Address Mark errors           000000000000 253   100   0     -

Logical drive name: C:\
Format: NTFS
Total size: 40541089792
Total free space: 6643462144

Logical drive name: D:\
Format: NTFS
Total size: 1734340608
Total free space: 1666990080

**Comment by DarthDestroyer** [comment]
I dont know, that this cpu is supported or not - by Intel or the Way, how OHM gets the Data!
You have to understand, that your CPU is 10 Years old!

Atleast, you get Mainboard Data ;)

Intel Ark https://ark.intel.com/products/29735/Intel-Celeron-Processor-430-512K-Cache-1_80-GHz-800-MHz-FSB
