### ISSUE TITLE
It is friendly to give openhardwaremonitor for c++ version，c# some don't understand like me thankyou author of  openhardwaremonitor

### ISSUE THREAD

**Issue by Vincenzou** [openhardwaremonitor/openhardwaremonitor#1056]

**Comment by msimic** [comment]
There is no C++ code. Are you are asking the author to rewrite the whole project into C++?

**Comment by DarthDestroyer** [comment]
That there is a C in both names, doesnt make it simple to "give you a c++" Version!

If you can understand c++ it isnt really hard to understand c#!
The other Direction is harder...

At this Point, there are to Options for you!
1. Do it by yourself!
2. Learn C#
