### ISSUE TITLE
The information from the CPU sensors is not displayed

### ISSUE THREAD

**Issue by FedyaLutkovski** [openhardwaremonitor/openhardwaremonitor#1058]
![image](https://user-images.githubusercontent.com/23061971/34299840-30bb84d8-e736-11e7-9f12-5dea715ea218.png)
Operating system - Windows 10
Literally yesterday everything worked, now why for some reason not. What could be the reason?

**Comment by FedyaLutkovski** [comment]
I am very sorry!
Run as administrator - everything worked! Thank you

**Comment by DarthDestroyer** [comment]
Without a Report, it is nearly impossible to say!

There could be many possible Problems, for example:
Problem with Driver / Service
MS Update 
Not allowed to run (removed admin priv.) 

A Report would list these on
