### ISSUE TITLE
SSL support

### ISSUE THREAD

**Issue by VahaC** [openhardwaremonitor/openhardwaremonitor#1059]
How about SSL certificates support?

**Comment by DarthDestroyer** [comment]
#964

**Comment by VahaC** [comment]
I'm talking not about site but about app

**Comment by DarthDestroyer** [comment]
lol, why arent you saying that you mean "digitally signing"?

There are several Reasons, why not!
1. To sign an Application, you need a Company to "vouch" you - that costs Money (Verisign, Thawte and so on)
2. You could sign it by yourself for free
3. It is not needed!

Let me combine all these Reasons into one Answer:
OHM is Open-Source! You can view the complete Code, can look what it does and why.
There is in no Part, a payed Service needed to "secure" it!
If OHM got self signed, who says that it's secure?! 

I hope you get the Point!

**Comment by VahaC** [comment]
thanks
