### ISSUE TITLE
Implementation problem

### ISSUE THREAD

**Issue by 110mat110** [openhardwaremonitor/openhardwaremonitor#1085]
I am trying to use library in my own aplication. I want to read CPU temp (and then send it to arduino) 

In app, I can see CPU temp 
![image](https://user-images.githubusercontent.com/33483661/36641290-b71cde1c-1a2d-11e8-8a92-9823cb0d7804.png)

but in my programmed app, I do not see nor temps nor clock
![image](https://user-images.githubusercontent.com/33483661/36641318-033d9930-1a2e-11e8-89a3-d73908d90bc7.png)

Code is simple.
https://paste.ofcode.org/jauWtisYf7mQaBkKE2jfxG

**Comment by rmattuschka** [comment]
Your App must have admin-rights to read this values too.

**Comment by 110mat110** [comment]
Admin-rights are not enough. I used 
`<requestedExecutionLevel level="highestAvailable" uiAccess="false" /> `

Now I can read everything I wanted
![image](https://user-images.githubusercontent.com/33483661/36641444-c71111c4-1a2f-11e8-844a-be01a8d7c720.png)
