### ISSUE TITLE
Support for Asus ROG STRIX Z370-E Gaming

### ISSUE THREAD

**Issue by Kolthor** [openhardwaremonitor/openhardwaremonitor#1098]
Would love support for said motherboard, which has no sensors listed in v0.8.0.3-alpha:
![v0.8.0.3-alpha screenshot](https://user-images.githubusercontent.com/25927780/38578171-71790982-3d03-11e8-8bdb-8660c1f3c72d.png)

BIOS lists the following temperature sensors:
- CPU Temperature
- Motherboard Temperature
- PCH Temperature
- T_Sensor Temperature
- EXT_Sensor1 Temperature
- EXT_Sensor2 Temperature
- EXT_Sensor3 Temperature

And the following fan speed sensors:
- CPU Fan Speed
- CPU Optional Fan Speed
- Chassis Fan 1 Speed
- M.2 Fan Speed
- Chassis Fan 2 Speed
- Extension Fan 1 Speed
- Extension Fan 2 Speed
- Extension Fan 3 Speed
- AIO Pump Speed

Attached report also generated using v0.8.0.3-alpha:
[OpenHardwareMonitor.Report.txt](https://github.com/openhardwaremonitor/openhardwaremonitor/files/1896061/OpenHardwareMonitor.Report.txt)

**Comment by DarthDestroyer** [comment]
Chip ID: Unknown Winbond / Nuvoton / Fintek with ID 0xD121 at 0x2E/0x2F

I see your nice writing and i think, you will handle that ;)
#981 should help, tested in #1060

**Comment by Kolthor** [comment]
PR #884 seems to do the trick, thanks!
![ohm2](https://user-images.githubusercontent.com/25927780/38697816-56310ca6-3e93-11e8-8c1d-2aa8168ef507.png)
(I renamed the fans manually, still need to figure out which temp is which)

Here's hoping it will make its way into the master.

**Comment by sir-hashpipe** [comment]
Hi, I tried this as well for my Asus Z370 Prime-A and it works. However the VCORE seems to be divided by 2? I have same results as in picture above. It's always showing half compared to HWiNFO or HWMonitor. Anyone knows how to fix this? And is it possible to get each individual Core VID from CPU also like HWiNFO? Thanks

**Comment by ThanOs47** [comment]
> PR #884 seems to do the trick, thanks!
> ![ohm2](https://user-images.githubusercontent.com/25927780/38697816-56310ca6-3e93-11e8-8c1d-2aa8168ef507.png)
> (I renamed the fans manually, still need to figure out which temp is which)
> 
> Here's hoping it will make its way into the master.

Can you send me the file for download ?

**Comment by moellerm** [comment]
This should be fixed in Open Hardware Monitor Version 0.9.2.
