### ISSUE TITLE
I'll donate $12 If you add Ryzen support

### ISSUE THREAD

**Issue by Chr0modynamic** [openhardwaremonitor/openhardwaremonitor#1104]
I just want to see cpu temps on my rainmeter skins that I use constantly. Adding support for ryzen would make my day.

Thanks

![ohm no cpu temps](https://user-images.githubusercontent.com/39423149/40262811-ba6f3056-5ad8-11e8-8d8f-1066ed66e2b4.PNG)
![ohm no cpu temps 1](https://user-images.githubusercontent.com/39423149/40262813-bba2cf82-5ad8-11e8-8256-674f2638236f.PNG)

**Comment by zzzkeil** [comment]
+1 Support for Ryzen
+1 Donate

**Comment by DarthDestroyer** [comment]
#962 #970 ?
The only possible Way to get this at the moment is self compiling these PRs!

**Comment by moellerm** [comment]
This should be fixed in OHM version 0.9.0 and later.
