### ISSUE TITLE
Incorrect total VRAM for Nvidia 1070ti

### ISSUE THREAD

**Issue by mtreis86** [openhardwaremonitor/openhardwaremonitor#1108]
My hardware report is coming back with the wrong total VRam on my 1070. Shows 4gigs where the 1070 has 8.

**Comment by DarthDestroyer** [comment]
could you upload a report?

**Comment by mtreis86** [comment]
I submitted a report to you through OHM Submit. If you would like another copy please send me your e-mail.

**Comment by mtreis86** [comment]
I may just be reading the report wrong. It clearly displays GPU Memory Total correctly. What is the GPU Memory (/nvidiagpu/0/clock/1) line in regards to?

**Comment by DarthDestroyer** [comment]
attach it here, please!

clock means clock ;-)

**Comment by mtreis86** [comment]
[MTReis86.OpenHardwareMonitor.Report.txt](https://github.com/openhardwaremonitor/openhardwaremonitor/files/2087094/MTReis86.OpenHardwareMonitor.Report.txt)

**Comment by DarthDestroyer** [comment]
looks fine for me?!

you could use the latest Version, but not really needed for you!

**Comment by mtreis86** [comment]
Okay I must be misunderstanding the file then. I will close this issue. Thanks.
