### ISSUE TITLE
All core temperatures missing for i7-7820X

### ISSUE THREAD

**Issue by syl20bou** [openhardwaremonitor/openhardwaremonitor#1114]
When I use openHardwareMonitor, despite recent updates to support Skylake, I get zeros for all 8 temperature sensors and package temperature as well. Other counters have proper values such as load values.

I use version 0.8.0.5 of the code. That version reads temperatures properly on my i7-4850HQ.

**Comment by highpec** [comment]
Same on i9-7940x, MSI x299m Carbon

Nuvoton NCT6795

**Comment by mrstandu33** [comment]
same here, you can download source files and compile it, it will normally work (I've seen a commit fixing this bug, but the latest release was before fix, so you have to compile it yourself (didn't try, as I don't have what it need to compile)

**Comment by mrstandu33** [comment]
I just compiled it, everything is working fine now (check screens). You can DL files here : https://we.tl/SEClsxVcIa

Hope you'll enjoy :p
![image](https://user-images.githubusercontent.com/22714562/42737875-43cc2326-887a-11e8-99a7-d90c8a9b6d51.png)

**Comment by highpec** [comment]
Very nice.  It works now...!

**Comment by mrstandu33** [comment]
mark as solved now ? 🤔
