### ISSUE TITLE
No Temp - new Intel Xeon Silver 4114

### ISSUE THREAD

**Issue by SearchForTheCode** [openhardwaremonitor/openhardwaremonitor#1127]
I attached an report for a new processor, that shows no temps..
Any chances for support on this?

[OpenHardwareMonitor.Report.txt](https://github.com/openhardwaremonitor/openhardwaremonitor/files/2286830/OpenHardwareMonitor.Report.txt)

If i can help i am gladly looking into it too, just need a direction!

**Comment by SearchForTheCode** [comment]
You can delete the issue.. i only tested with 0.8.0 .

it works with the latest build  0805-alpha !

**Comment by seema84** [comment]
you can close it self
