### ISSUE TITLE
No CPU-Temperature on Lenovo ThinkCentre m720t with Intel i3-8100 CPU

### ISSUE THREAD

**Issue by gunnarhaslinger** [openhardwaremonitor/openhardwaremonitor#1135]
Lenovo ThinkCentre m720t with Intel i3-8100 CPU
No CPU Temperature shown:
![openhardwaremonitor_lenovo-thinkcentre-m720t_intel_i3-8100](https://user-images.githubusercontent.com/8940065/45871662-542c5f80-bd8e-11e8-9741-41eee0ab02fd.jpg)

Here is the saved Report:
[OpenHardwareMonitor_Lenovo-ThinkCentre-m720t_Intel_i3-8100.Report.txt](https://github.com/openhardwaremonitor/openhardwaremonitor/files/2404648/OpenHardwareMonitor_Lenovo-ThinkCentre-m720t_Intel_i3-8100.Report.txt)

Would be very nice and helpful, if this System could be supported.
**Thank you, for your great Tool and Support!**

**Comment by winner69** [comment]
http://openhardwaremonitor.org/files/openhardwaremonitor-v0.8.0.3-alpha.zip

**Comment by gunnarhaslinger** [comment]
Thanks, great!
