### ISSUE TITLE
Fans not showing

### ISSUE THREAD

**Issue by ukheather** [openhardwaremonitor/openhardwaremonitor#1151]
I have a Asus ROG GL703GM laptop with Intel® Core™ i7-8750H, Nvidia 1060 but the fans aren't showing even in 0.8.3

I have 2 fans, one for CPU and one for GPU

**Comment by DarthDestroyer** [comment]
Without a Report added to you Issue it is pretty hard to say

**Comment by moellerm** [comment]
This can't be fixed without additional information.
