### ISSUE TITLE
CPU temp i5-9600k

### ISSUE THREAD

**Issue by 01username** [openhardwaremonitor/openhardwaremonitor#1156]
CPU temps do not appear for this cpu. 

https://imgur.com/a/5Dru2wn

**Comment by DarthDestroyer** [comment]
You have two Options!

1. http://openhardwaremonitor.org/files/openhardwaremonitor-v0.8.0.3-alpha.zip

2. Please add a Report!

Without that, it is impossible to help you

Regards

**Comment by 01username** [comment]
Works perfectly with the alpha. Here is the report if you wish to investigate : 

[OpenHardwareMonitor.Report.txt](https://github.com/openhardwaremonitor/openhardwaremonitor/files/2761816/OpenHardwareMonitor.Report.txt)
