### ISSUE TITLE
No clocks or temperatures for Intel i7-7700

### ISSUE THREAD

**Issue by Soraldor** [openhardwaremonitor/openhardwaremonitor#1159]
I can't read the clocks or temperatures for an Intel i7-7700 on an ASUS PRIME Z270-K mainboard in version 0.8.0.5-Alpha. Should I use 0.8.0.3 instead? Report included - thanks in advance

[OpenHardwareMonitor.Report.txt](https://github.com/openhardwaremonitor/openhardwaremonitor/files/2736361/OpenHardwareMonitor.Report.txt)

**Comment by DarthDestroyer** [comment]
Both Versions will fail without Admin!

Try to start it as Admin, please

**Comment by Soraldor** [comment]
Sorry for my late response. That was the problem. Thank you! 👍
