### ISSUE TITLE
SSD NVMe temperature not shown

### ISSUE THREAD

**Issue by aster94** [openhardwaremonitor/openhardwaremonitor#1162]
I have a samsung 970 and the temperature isn't available

**Comment by aster94** [comment]
hi,
you are right i just searched in the open issues and i didn't found any , i didn't check the PR

i have zero knowledge of C#, I cloned the fork with the fix and tried to run it with `msbuild.exe` to see if that was working but I got some errors since `resgen.exe` is missing so i downloaded windows SDK but no lucks

i think i will just wait the next release of the software to test it :(

**Comment by DarthDestroyer** [comment]
Just install Visual Studio with C# and everything should work!

Fork it, merge the pull Request ive mentioned and it should run after that!

No Problem! Sorry that ive said that so rude... But you see millions of "issues" which are already solved or atleast there is a workaround available!

With VS, you should be able to get it working! ;-)

**Comment by aster94** [comment]
i confirm it is working, I am closing the issue, thanks a lot @DarthDestroyer
