### ISSUE TITLE
System tray icons freeze if being connected with remote desktop

### ISSUE THREAD

**Issue by LionetChen** [openhardwaremonitor/openhardwaremonitor#1163]
I have setup tray icon to show temperature and CPU usage for my work PC from local login. At first everything works fine. Tray icon is updated every a few seconds. Then I logged in my work PC from home with Remote Desktop (the PC is on the whole time. I only lock it when leaving office). The tray icon just freeze there, not updating. Right-click and double-click still work, bringing context menu and the main windows respectively. Only the display value /image is not changing any more. I have to close the program and reopen for them to start refreshing again.

**Comment by DarthDestroyer** [comment]
Duplicate of #1092

**Comment by LionetChen** [comment]
It's confirmed a duplicate. #1092 points to #1093 then to https://github.com/LibreHardwareMonitor/LibreHardwareMonitor
