### ISSUE TITLE
No clocks or temp for intel core i7 6820HQ

### ISSUE THREAD

**Issue by sirKitKat** [openhardwaremonitor/openhardwaremonitor#1174]
Screenshot:
![image](https://user-images.githubusercontent.com/1853002/54761414-5a42b200-4bf2-11e9-9b12-6d058f7d236a.png)

Report:
[OpenHardwareMonitor.Report.txt](https://github.com/openhardwaremonitor/openhardwaremonitor/files/2992633/OpenHardwareMonitor.Report.txt)

Thanks!

**Comment by DarthDestroyer** [comment]
Download the latest Version and run as Admin ;-)



http://openhardwaremonitor.org/files/openhardwaremonitor-v0.8.0.3-alpha.zip

**Comment by sirKitKat** [comment]
Thx, I was running the latest version (0.8.0 beta) and running that version as admin did the trick.
Suggestion: when hovering over the empty values and you are not running the app as admin, maybe a tool-tip could appear with the suggestion to run the program as admin to view the missing values?
