### ISSUE TITLE
Radeon VII no data

### ISSUE THREAD

**Issue by dnikonov** [openhardwaremonitor/openhardwaremonitor#1187]
Hey.
OHM does not give out data on the AMD Radeon VII card.
What data do you need to send?

![debc4f278462c39a15e0a6bada9b345d](https://user-images.githubusercontent.com/3995104/59551614-ab660600-8f95-11e9-9e67-739e7b4634b5.jpg)

**Comment by DarthDestroyer** [comment]
You could add a Report which provide a little bit more info...

Attach the textfile to that issue ;-)

**Comment by dnikonov** [comment]
Attached the report.

[OpenHardwareMonitor.Report.txt](https://github.com/openhardwaremonitor/openhardwaremonitor/files/3293104/OpenHardwareMonitor.Report.txt)

**Comment by dnikonov** [comment]
Hey.
Any news on the issue?

**Comment by binary100100** [comment]
I'm having the exact same issue with RX 5700 cards. Perhaps it's because Navi?

**Comment by moellerm** [comment]
Please try with this test version
http://openhardwaremonitor.org/files/openhardwaremonitor-v0.9.1.1-alpha.zip
and submit a report by selecting File -> Submit Report... from the menu.

**Comment by dnikonov** [comment]
RTX 2060 - everything is fine
Radeon VII - fan speed in RPM, please add as a percentage, like other cards

[RTX 2060.txt](https://github.com/openhardwaremonitor/openhardwaremonitor/files/4270565/RTX.2060.txt)
[RTX 2060 2.txt](https://github.com/openhardwaremonitor/openhardwaremonitor/files/4270564/RTX.2060.2.txt)
[Radeon VII.txt](https://github.com/openhardwaremonitor/openhardwaremonitor/files/4270566/Radeon.VII.txt)

**Comment by moellerm** [comment]
Thank you for your feedback. I have added some additional sensors to the OHM release version 0.9.2. Fan speed as percentage can be read by OHM, but seems not to be provided by the GPU driver in your case.
