### ISSUE TITLE
CPU Temperatures for Ryzen 7 3700X

### ISSUE THREAD

**Issue by FoxiesFury** [openhardwaremonitor/openhardwaremonitor#1194]
Missing temperatures for Ryzen 7 3700X. Here is report:
[OpenHardwareMonitor.Report.txt](https://github.com/openhardwaremonitor/openhardwaremonitor/files/3452986/OpenHardwareMonitor.Report.txt)

Thank you for your attention. :)

**Comment by DarthDestroyer** [comment]
Did you tried #970?

**Comment by FoxiesFury** [comment]
I tried it now. Does not work.

**Comment by SearchForTheCode** [comment]
Can you try out the latest LibreHardwareMonitor?

**Comment by FoxiesFury** [comment]
I downloaded and extracted it but how do I start it? :O

**Comment by SearchForTheCode** [comment]
Oh you have no Visual Studio to build it? Please use this package to test. Just start the OpenHardwareMonitor.exe
[LibreOHM.zip](https://github.com/openhardwaremonitor/openhardwaremonitor/files/3472637/LibreOHM.zip)

**Comment by FoxiesFury** [comment]
It works now! Thanks a lot!

**Comment by SearchForTheCode** [comment]
Great news, so Ryzen 7 3700x is also handled by this AMD changes :)

**Comment by FoxiesFury** [comment]
Screenshot and report:

![Screenshot](https://user-images.githubusercontent.com/34405243/62636674-42b65c80-b93a-11e9-8fb1-f7e62cc5a3fc.jpg)
[OpenHardwareMonitor.Report.txt](https://github.com/openhardwaremonitor/openhardwaremonitor/files/3477810/OpenHardwareMonitor.Report.txt)
