### ISSUE TITLE
SENSOR_1 probe sensor not showing for ASUS Ranger VII matherboard.

### ISSUE THREAD

**Issue by Ndrinta** [openhardwaremonitor/openhardwaremonitor#1200]
Hello,
using the sw since ages and it has always worked beautifully. I now bought a probe sensor and added it on the SENSOR_1 probe port. The temperature value wasn't shown in the Open Hardware Monitor interface so I downloaded Fan Expert 3 and I could see that there is showed regularly so I assume there is no issue with the probe itself but rather a problem in the SW.

Is there any chance you can look into this? I would be glad to compensate you guys for the time spent on this fix! I'm serius.
Thanks

**Comment by DarthDestroyer** [comment]
Could you attach a Report into your Issue?

That would help to identify the used Hardware!

Regards

**Comment by Ndrinta** [comment]
Sure I can!

[OpenHardwareMonitor.Report.txt](https://github.com/openhardwaremonitor/openhardwaremonitor/files/3585077/OpenHardwareMonitor.Report.txt)

**Comment by DarthDestroyer** [comment]
You are a little bit outdated ;)

Have you tried the latest Version, too? 
http://openhardwaremonitor.org/files/openhardwaremonitor-v0.8.0.3-alpha.zip

**Comment by Ndrinta** [comment]
Yes I did yesterday. Since there was no more sensor shown I didn't bother to update.

Il sab 7 set 2019, 23:08 Dan Neel <notifications@github.com<mailto:notifications@github.com>> ha scritto:

You are a little bit outdated ;)

Have you tried the latest Version, too?
http://openhardwaremonitor.org/files/openhardwaremonitor-v0.8.0.3-alpha.zip
