### ISSUE TITLE
AMD RX 5700 GPU Not showing any details

### ISSUE THREAD

**Issue by binary100100** [openhardwaremonitor/openhardwaremonitor#1203]
Version 0.8.0.3 Alpha shows the cards but no data.

Windows 10 Professional (ver 1809)
Adrenaline Driver 19.9.2

[OpenHardwareMonitor.Report.txt](https://github.com/openhardwaremonitor/openhardwaremonitor/files/3629017/OpenHardwareMonitor.Report.txt)

**Comment by sebastian-dev** [comment]
try out: https://github.com/aquacomputer/LibreHardwareMonitor/releases
or: https://github.com/LibreHardwareMonitor/LibreHardwareMonitor

**Comment by binary100100** [comment]
Nope. Same result. Nothing for RX 5700 XT cards.
[LibreHardwareMonitor.Report.txt](https://github.com/openhardwaremonitor/openhardwaremonitor/files/3644215/LibreHardwareMonitor.Report.txt)

**Comment by moellerm** [comment]
I have started working on this. Please download this test version
http://openhardwaremonitor.org/files/openhardwaremonitor-v0.9.1.1-alpha.zip
and submit a report by selecting File -> Submit Report... from the menu.

**Comment by moellerm** [comment]
This issue has been fixed in OHM version 0.9.2.
