### ISSUE TITLE
CPU Temperatures for Ryzen 5 3600X

### ISSUE THREAD

**Issue by FoxiesFury** [openhardwaremonitor/openhardwaremonitor#1209]
Missing temperatures for Ryzen 5 3600X.

**Comment by sebastian-dev** [comment]
https://github.com/LibreHardwareMonitor/LibreHardwareMonitor

**Comment by FoxiesFury** [comment]
I can't run this :O

**Comment by sebastian-dev** [comment]
?? a few mor informations ;)

**Comment by FoxiesFury** [comment]
I have no visual studio to build it.
Same thing happened here: https://github.com/openhardwaremonitor/openhardwaremonitor/issues/1194
SearchForTheCode had exe file.

**Comment by sebastian-dev** [comment]
![lhm](https://user-images.githubusercontent.com/7968213/66777669-cf950d80-eec9-11e9-9897-2de8c01956c2.PNG)

**Comment by moellerm** [comment]
Open Hardware Monitor Version 0.9.1 should support the Ryzen 5 3600X CPU.

https://openhardwaremonitor.org/downloads/
