### ISSUE TITLE
HardwareMonitor wont start.

### ISSUE THREAD

**Issue by Fhosho** [openhardwaremonitor/openhardwaremonitor#1211]
This became a problem yesterday. (2019-10-15) 
I have HWM to start up with windows but get this error every time.. i try to start it as admin too but it's the same.. Tryed different versions also. 
![Capture](https://user-images.githubusercontent.com/22599256/66998419-8238bc00-f0d4-11e9-9865-2d480ba0743e.PNG)
Anyone else with the same problem or with a fix ? I miss my gadget!!

**Comment by DarthDestroyer** [comment]
For the first step, i would rename the directory and start it as admin.

If that doesnt work, it could help to delete the config and start fresh... 

there is something wrong with the config and/or with the start procedure

**Comment by Fhosho** [comment]
@DarthDestroyer 
hm, did both of your suggestions, did not seem to solve the problem, still the same.

**Comment by DarthDestroyer** [comment]
so it doesnt even start normally?

**Comment by Fhosho** [comment]
Nope.
Same error as the picture above.

**Comment by Fhosho** [comment]
Okay so apparently nothing has worked for me.
But i found Open Hardware Monitor v0.8.0.5 ALPHA.
Wich at first didn't work either (at first)...
Got the same error as above but about one hour later when tried executing the same exe it magically opened up! so it's working now! 
(I hope it works when i reset my pc later) we will see about that.

**Comment by turbatus** [comment]
Same here, same error! 
![image](https://user-images.githubusercontent.com/8330709/71578632-4620cf00-2af9-11ea-8418-47c1977cca4d.png)

**Comment by Fhosho** [comment]
> Same here, same error!
> ![image](https://user-images.githubusercontent.com/8330709/71578632-4620cf00-2af9-11ea-8418-47c1977cca4d.png)

This error is now fixed for me, after some restarts of my pc It’s back to normal. Just wait and see if it launch normally after you restart your pc.

**Comment by Tenn0** [comment]
For me, i configured OHW to startup with windows since i use it to monitor my temps in home assistant. But the above error appears also for me most of the time. But sometimes when my pc starts OHW starts correctly.

**Comment by turbatus** [comment]
For me it works, now. Looks that it only needs some time to get to know your OS. :)

**Comment by XcOM987** [comment]
![image](https://user-images.githubusercontent.com/47461886/152775598-4156391f-efd8-4924-83bb-0e8132f0ea96.png)
Not sure if anyone has worked on this, but it's still an issue, I can replicate the fault on my server 2019 box with every version of Open Hardware available, reset the config, tried multiple config setups, compat mode, nothing works, get the same error every time
