### ISSUE TITLE
No temp for Intel Xeon E5-1620 v3

### ISSUE THREAD

**Issue by Nebukadnezzar13** [openhardwaremonitor/openhardwaremonitor#1215]
Cant find temperature values for Intel Xeon E5-1620 v3
[OpenHardwareMonitor.Report.txt](https://github.com/openhardwaremonitor/openhardwaremonitor/files/3788951/OpenHardwareMonitor.Report.txt)

**Comment by moellerm** [comment]
There is some issue with installing the driver on your system. It reports the following when trying to load the driver:

Die digitale Signatur dieser Datei kann nicht überprüft werden. Möglicherweise wurde durch eine kürzlich durchgeführte Hardware- oder Softwareänderung eine falsch signierte oder beschädigte Datei oder eine Datei, bei der es sich um böswillige Software aus einer unbekannten Quelle handelt, installiert. 

Maybe some antivirus software or similar is blocking this. The hardware access driver that OHM uses has not changed in years.
