### ISSUE TITLE
CPU temp not showing on i7-7800X

### ISSUE THREAD

**Issue by GaxzDK** [openhardwaremonitor/openhardwaremonitor#1219]
Tried getting the quick fix for 7700K but it didn't work :(

**Comment by DarthDestroyer** [comment]
Did you have tried http://openhardwaremonitor.org/files/openhardwaremonitor-v0.8.0.3-alpha.zip?

If not, please add a Report!

**Comment by GaxzDK** [comment]
Thank you! I will test it later

tir. d. 3. dec. 2019 10.07 skrev Dan Neel <notifications@github.com>:

**Comment by GaxzDK** [comment]
Sadly it didn't work.. :(

**Comment by moellerm** [comment]
This should be fixed in the latest version https://openhardwaremonitor.org/files/openhardwaremonitor-v0.9.1.zip
