### ISSUE TITLE
Asus x470 prime pro no temps :(

### ISSUE THREAD

**Issue by mittyredstar** [openhardwaremonitor/openhardwaremonitor#1229]
[OpenHardwareMonitor.Report.txt](https://github.com/openhardwaremonitor/openhardwaremonitor/files/4139395/OpenHardwareMonitor.Report.txt)

**Comment by DarthDestroyer** [comment]
You are a little bit outdated...
Try: https://openhardwaremonitor.org/files/openhardwaremonitor-v0.9.2.3-alpha.zip

**Comment by mittyredstar** [comment]
big THX :)
