### ISSUE TITLE
https://openhardwaremonitor.org/ not working ...

### ISSUE THREAD

**Issue by tavoweb** [openhardwaremonitor/openhardwaremonitor#1231]
Can someon share the software ? oficial site down ...
![Ekrano kopija (1)](https://user-images.githubusercontent.com/5119895/74609780-05efcd00-50f6-11ea-8b9b-b3d3ba7a202c.png)

**Comment by deVDem** [comment]
Hi.wait a few minutes

**Comment by deVDem** [comment]
[Debug.zip](https://github.com/openhardwaremonitor/openhardwaremonitor/files/4210513/Debug.zip)
I built a Debug version specifically for you and put the files in a zip archive, because I think that you need more than just an exe file.

**Comment by deVDem** [comment]
And, by the way, the site is quite working
