### ISSUE TITLE
I9 9900k Temperatures with c#

### ISSUE THREAD

**Issue by floriskn** [openhardwaremonitor/openhardwaremonitor#1232]
I can see the CPU temperatures in the application but I can't get them with c#. I use the 0.8.0.5 Alpha version.
![image](https://user-images.githubusercontent.com/48930050/74612305-80bfe480-5104-11ea-9a7f-57779d4e3753.png)
And this is the code:
![image](https://user-images.githubusercontent.com/48930050/74612314-959c7800-5104-11ea-9c03-d1d1020b3882.png)
For example, if I do "SensorType.Load" then I will see the correct values.

Edit:
With the i9 I can't get any data via the code at all, except for the load.

**Comment by moellerm** [comment]
You need to make sure that your code is run with admin rights, for example by including an app.manifest file: https://github.com/openhardwaremonitor/openhardwaremonitor/blob/master/Resources/app.manifest
And you need to call IHardware .Update() before reading the sensor values, to get (updated) values.
