### ISSUE TITLE
Gadget Bars Don't Scale

### ISSUE THREAD

**Issue by dallas7** [openhardwaremonitor/openhardwaremonitor#1237]
i9-9900K Z390 Win10pro OHM 0.9.2

The clocks CPU core bars in the gadget aren't representative of the values.

In the screenshot, they're always those tiny levels on the left no matter what the MHz is.  The shot was taken during the conversion of a 32GB m2ts video to 4GB MP4.  Surely the bars should span about half way.

Thanks!

[OHMreport.txt](https://github.com/openhardwaremonitor/openhardwaremonitor/files/4310222/OHMreport.txt)

![OHM-CORE](https://user-images.githubusercontent.com/12632725/76278904-0c331e00-624a-11ea-9396-bdefb36e7469.jpg)

**Comment by moellerm** [comment]
The clocks should be displayed as "2600 MHz" and not as bars. The bars are for the load sensors.

**Comment by dallas7** [comment]
Thanks for the fast reply.

It's been a long time since I've dug into the Gadget options and got my CPU Core# "show in" mixed up.
