### ISSUE TITLE
DPI issues on 4k screens

### ISSUE THREAD

**Issue by andresmorago** [openhardwaremonitor/openhardwaremonitor#1248]
When opening the latest exe version file on windows, the window that appears is having problems scaling its content. see attached image

https://imgur.com/2F3ZzRZ

**Comment by rocboronat** [comment]
Same on Windows 10 :·)

![image](https://user-images.githubusercontent.com/456499/79914688-f490ad00-8425-11ea-8b8e-947462c03c96.png)

**Comment by moellerm** [comment]
This should be fixed in version 0.9.4

**Comment by rocboronat** [comment]
Just tried it and yes, it is. Thanks a lot, @moellerm !
