### ISSUE TITLE
Motherboard Fans speeds sensors wont load if value = 0

### ISSUE THREAD

**Issue by javguit** [openhardwaremonitor/openhardwaremonitor#1249]
Just found out that the fan sensor in the motherboard hardware wont load if its value is 0. 

The line 1529 in the file SuperIOHardware.cs file is an if clause that if bypassed ( or removed ) the sensors will load under the motherboards subhardware and show the value of 0. I'd rather have this than a non existent sensor.

![OHM-fans-not-loading-issue](https://user-images.githubusercontent.com/63629902/79187651-3cdf1800-7df3-11ea-82d3-3e222e73ca38.jpg)

is this intended?

**Comment by moellerm** [comment]
It was originally intended, as some mainboards had more fan control/monitor channels in the super I/O chip than what was really exposed as pin connector (to connect actual fans). At the same time, stopping fans (zero RPM) was rarely supported, so zero RPM most likely meant no fan connected (or not even a fan pin connector on the mainboard).

I think we could change this, now that there is also the option to hide a sensor (if not useful to the user). 

Anyone has other preferences?
