### ISSUE TITLE
Control fan IT8720F - Set to ON/OFF and there's no way to change it to software control

### ISSUE THREAD

**Issue by javguit** [openhardwaremonitor/openhardwaremonitor#1250]
Im having an issue with this controller and manual fan control. Debugging it with SpeedFan I found out that OHM wont change the control mode if it is set to ON/OFF, which, according to the IT8720F datasheet, is controlled by the 0x13 Environment Controller Register. Bits 0 to 2 of that register control the output mode selection for each fans, and if set to 0 there's no way to control the fan with the current implementation of OHM, nor change it to 1 to get control of it.
Quick workaround for me was to change the specific value of the 0x13 register with an OR operand when trying to change the pwm value.
This is my new SetControl subroutine in the \Hardware\LPC\IT87XX.cs file

 ```
private readonly byte FAN_MAIN_CTRL_REG = 0x13; //create the constant of the register


 public void SetControl(int index, byte? value) {
      if (index < 0 || index >= controls.Length)
        throw new ArgumentOutOfRangeException("index");
      if (!Ring0.WaitIsaBusMutex(10))
        return;
      if (value.HasValue) {
        bool valid;
        byte auxControlType = 0; //added
        SaveDefaultFanPwmControl(index);
        switch (index)
        {
            case 0:
                auxControlType = 0b00000001; //Control for the first fan
                break;
            case 1:
                auxControlType = 0b00000010; //Control for the second fan
                 break;
            case 2:
                auxControlType = 0b00000100; //Control for the third fan
                break;
            default:
                auxControlType = 0;
                break;
        }
                WriteByte(FAN_MAIN_CTRL_REG, (byte)(auxControlType | ReadByte(FAN_MAIN_CTRL_REG, out valid))); //added
        // set output value
                WriteByte(FAN_PWM_CTRL_REG[index], (byte)(value.Value >> 1));  
      } else {
        RestoreDefaultFanPwmControl(index);
      }
      Ring0.ReleaseIsaBusMutex();
    }
```
![IT8270F](https://user-images.githubusercontent.com/63629902/79256062-c1668080-7e5d-11ea-98cc-d0a93a135dd1.png)

**Comment by moellerm** [comment]
This should be fixed in commit 7bf4f655d2c3ad9b660b6703c632b1d5694778ca. Can you please test and confirm?
