### ISSUE TITLE
Bogus Temperature reporting 

### ISSUE THREAD

**Issue by Abeiis** [openhardwaremonitor/openhardwaremonitor#1262]
Under the Motherboard {ASUS RAMPAGE V EXTREME} Temperature, it shows a very high temp. for #3,4, and 6. I do not understand what these temps. represent (see attached) and what are they to rectify them.
I am hoping that once ID the motherboard, you can ID each component that these temps are reporting from....PLEASE, Thanks!
![2020-04-30_103121](https://user-images.githubusercontent.com/15078990/80741970-696f8100-8acf-11ea-9884-1d4c66dd42ea.png)

**Comment by moellerm** [comment]
You can try to identify the temperatures reported from the mainboard (NCT6791D) by comparing with values reported in the BIOS and/or official tools from ASUS. Unfortunately, there is no public documentation available as to what these sensor channels are connected to (if anything useful at all).
