### ISSUE TITLE
Feature request: Persist settings across a restart of the application

### ISSUE THREAD

**Issue by lbreuss** [openhardwaremonitor/openhardwaremonitor#1265]
When I restart the application, the previous configuration is lost, all settings are to their default again.

This affects at least the following settings:
* Menu checkmarks like Minimize to Tray, and Hardware selection

**Comment by moellerm** [comment]
Settings should be persisted when the application exits to a file called OpenHardwareMonitor.config. It's a simple xml file with a list of keys/values.

Maybe make sure to manually exit the application once (File -> Exit), in case the system does not provide enough time to write settings to the file when the system is shutting down.

Let me know if the settings are not written at all, or if it is only a problem when the system is shutting down.

**Comment by lbreuss** [comment]
OK, todays tests show that the settings file is written. 
Menu checkmark is persisted indeed.
Cannot reproduce, sorry for the hassle.
