### ISSUE TITLE
Feature request: Persist collapsed state of nodes in current view 

### ISSUE THREAD

**Issue by lbreuss** [openhardwaremonitor/openhardwaremonitor#1266]
Persist the state of collapsed nodes, so the nodes will show up collapsed on the next restart.

Upon hardware changes, per default, new nodes may keep showing up expanded per default, I think that's useful.

In addition to the above, it would be nice to be able to hide nodes from the tree. And of course unhide them somehow -- a reset view function as a simple implementation.

**Comment by moellerm** [comment]
This has been implemented in commit 87c6f02d33e2226a0c8619b7d1817d1a92b48a55
You can test it in the just released OHM version 0.9.3

You can already hide individual sensors in the tree. When all sensors on a type node are hidden, then also the type node will be hidden. The menu "View -> Show Hidden Sensors" allows to show hidden senors once more.
