### ISSUE TITLE
System.IO.FileNotFoundException on Computer.Open()

### ISSUE THREAD

**Issue by ottovilles** [openhardwaremonitor/openhardwaremonitor#1273]
I have been trying to use hardware API that OpenHardwareMonitor.dll offers in my project without success. The problem that I encounter is

`"Could not load file or assembly 'System.Management, Version=2.0.0.0, Culture=neutral, PublicKeyToken=b03f5f7f11d50a3a'. The system cannot find the file specified."`

from 
```
Computer computer = new Computer();
computer.Open();
```

I have tried to run Visual Studio 2019 Community Edition as administrator and I have tried to add Application Manifest File into my application and use 
`<requestedExecutionLevel  level="highestAvailable" uiAccess="false" />` 
without success.

If I add System.Management package to my project, the FileNotFoundException will change to
`
Method not found: 'System.Threading.Mutex System.Threading.Mutex.OpenExisting(System.String, System.Security.AccessControl.MutexRights)'."} | System.MissingMethodException
`

and it seems to point at
`OpenHardwareMonitor.Hardware.Ring0.Open()`

any ideas what might cause this?

OHM .exe runs normally and shows all the temperatures correctly, so I'm not sure if this has anything to do with privileges?

**Comment by moellerm** [comment]
Try to compile and run the OHM application as starting point and debug from there.
