### ISSUE TITLE
Fan speed control loses track while sleep

### ISSUE THREAD

**Issue by mhk76** [openhardwaremonitor/openhardwaremonitor#1276]
After my computer gets back from sleep, manual fan controls have lost their control over the speed. Menu still shows that the manual control is on, but it really isn't. I have to change the value and it works again.

Basically this needs tracking of Windows' power mode event (SystemEvents.PowerModeChanged) and reset the manual control values when power gets back.

**Comment by moellerm** [comment]
Can you please attach a report file? Create one with File -> Save Report...

Otherwise it is difficult to know which hardware is affected by this.

**Comment by Ale-Rock** [comment]
Hi, I join the conversation that I'm having the same problem. how can it be solved?
I attach the report file.
[OpenHardwareMonitor.Report.txt](https://github.com/openhardwaremonitor/openhardwaremonitor/files/4638664/OpenHardwareMonitor.Report.txt)

**Comment by moellerm** [comment]
I have tried to fix this in a new alpha version:

https://openhardwaremonitor.org/files/openhardwaremonitor-v0.9.3.3-alpha.zip

This version resets the complete OHM hardware tree when the system resumes from sleep.

Please let me know if this works as intended.

**Comment by mhk76** [comment]
Works for me. Great work.

**Comment by Ale-Rock** [comment]
It works for me too. Thank you very much.

**Comment by moellerm** [comment]
Thx for the feedback.
