### ISSUE TITLE
AMD FX-8800P CPU TEMP doesn't appear

### ISSUE THREAD

**Issue by zenoaghaz** [openhardwaremonitor/openhardwaremonitor#1280]
![AMD FX-8800P](https://user-images.githubusercontent.com/13913591/82302080-5d8c2600-99ce-11ea-9629-2f8e411c85f5.png)

**Comment by moellerm** [comment]
Please try with this version https://openhardwaremonitor.org/files/openhardwaremonitor-v0.9.3.4-alpha.zip

**Comment by zenoaghaz** [comment]
> Please try with this version https://openhardwaremonitor.org/files/openhardwaremonitor-v0.9.3.4-alpha.zip

thanks for reply. 
problem solved.
![Untitled_2](https://user-images.githubusercontent.com/13913591/82409426-f7ada600-9a82-11ea-96e4-95f27453d891.png)

**Comment by moellerm** [comment]
Thx for the feedback.
