### ISSUE TITLE
CPU temperature not showing for i7-10875h

### ISSUE THREAD

**Issue by nnchiew** [openhardwaremonitor/openhardwaremonitor#1281]
There is no showing for the CPU (ex: clocks, temperature etc. except load)
[OpenHardwareMonitor.Report.txt](https://github.com/openhardwaremonitor/openhardwaremonitor/files/4671509/OpenHardwareMonitor.Report.txt)

**Comment by moellerm** [comment]
Please try with this alpha version: https://openhardwaremonitor.org/files/openhardwaremonitor-v0.9.3.5-alpha.zip

**Comment by nnchiew** [comment]
Thank you, it solves the problem.  Sent from Mail for Windows 10 From: Michael MöllerSent: Saturday, 23 May 2020 8:44 pmTo: openhardwaremonitor/openhardwaremonitorCc: nnchiew; AuthorSubject: Re: [openhardwaremonitor/openhardwaremonitor] CPU temperature not showing for i7-10875h (#1281) Please try with this alpha version: https://openhardwaremonitor.org/files/openhardwaremonitor-v0.9.3.5-alpha.zip—You are receiving this because you authored the thread.Reply to this email directly, view it on GitHub, or unsubscribe.

**Comment by moellerm** [comment]
Thx for the feedback.
