### ISSUE TITLE
Log file not properly readable, its a chaos?

### ISSUE THREAD

**Issue by 0lm** [openhardwaremonitor/openhardwaremonitor#1296]
Hi.

I dont know what I am doing wrong, but the csv Log file is kind of a chaos. I open it with Excel and it isnt displayed properly in tables and stuff, but just a bunch of numbers and text written literally next to each other, without being able to find out where a section starts and where one ends.

Am I ding something wrong here, or is this the only way how OHM works?

**Comment by nassaleh** [comment]
Can you paste a couple of lines of the CSV so we can see whats wrong?
