### ISSUE TITLE
Different temperature report for one core between Open Hardware Monitor and HWMonitor

### ISSUE THREAD

**Issue by vsiles** [openhardwaremonitor/openhardwaremonitor#1356]
Hi !
First, thank you for this amazing piece of software. I was using CPUID HWMonitor until I wanted some graphics, so I switched to your software.
I'm very pleased, but I'm noticing a single differences between the two tools: one of the core of my i7 is showing 40° C on HWMonitor and more than 85° C on OHM. As far as I can tell, this is the only difference between the reports:

<img width="612" alt="temp cpu" src="https://user-images.githubusercontent.com/7124672/97071330-eb081d80-15df-11eb-917c-2d61a84a448d.png">

Which one should I trust ? Is there an known issue that would explain this ?

**Comment by moellerm** [comment]
The temperatures shown in your Open Hardware Monitor screenshot are not the CPU core temperatures. The shown temperature values are from the Nuvoton super I/O chip.
