### ISSUE TITLE
AMD RYZEN 9 5900X clocks  not displayed

### ISSUE THREAD

**Issue by anjisZhou** [openhardwaremonitor/openhardwaremonitor#1371]
![图片](https://user-images.githubusercontent.com/25604955/100039706-be466080-2e40-11eb-8420-9a786a92cc52.png)

**Comment by kmshort** [comment]
I concur, I also have a 5900x and see the same thing.
CPU temperature not displayed either.

**Comment by yunyuyuan** [comment]
行了，知道你有5900x了

**Comment by GetJon** [comment]
Ryzen 7 5800x on a Gigabyte B550 AORUS ELITE V2 with OpenHardwareMonitor version 0.9.5 also showing just the CPU Load, no temperatures.

**Comment by rmattuschka** [comment]
You can try this Pull request "#1373 Update to Zen3 (similar to Zen2)"

**Comment by anjisZhou** [comment]
> 
> 
> You can try this Pull request "#1373 Update to Zen3 (similar to Zen2)"

let me try

**Comment by moellerm** [comment]
This should be fixed in the latest version 0.9.6.
