### ISSUE TITLE
AMD Ryzen temperatures monitoring

### ISSUE THREAD

**Issue by ATRedline** [openhardwaremonitor/openhardwaremonitor#1374]
I need to get temperatures of CPU and GPU throw OpenHardwareMonitorLib, and i made the simple code:
![1](https://user-images.githubusercontent.com/16624304/101361031-e067c600-38b7-11eb-91f8-ce630a58b434.jpg)

 It works well on intel CPUs, but i asked friend to test it, and somewhy, on his ryzen processor, my code is not seen temperatures of CPU:
![2](https://user-images.githubusercontent.com/16624304/101361118-04c3a280-38b8-11eb-8141-f35598fdfc9f.png)

 but in the OpenHardwareMonitor app this sensor exists:
![3](https://user-images.githubusercontent.com/16624304/101361139-09885680-38b8-11eb-8818-fc1fdfe792d9.png)

 How i can get data from Ryzen termal sensor??

**Comment by ATRedline** [comment]
ok. The solution was to run this app with admin rights...

**Comment by moellerm** [comment]
Admin rights are required for certain sensors, not much we can do atm.
