### ISSUE TITLE
Feature Request: post json data to remote server

### ISSUE THREAD

**Issue by boomsya** [openhardwaremonitor/openhardwaremonitor#1407]
hi
can you add support periodically POST JSON data to a remote server to configured URL?
this is very helpful for monitoring systems

**Comment by dan0delellis** [comment]
FYI, you can curl a json if you are running the web server. 
If OHM is running on a host with IP 10.0.0.100 and is presenting on port 8085, you can do `curl http://10.0.0.100:8085/data.json` and it will spit out a JSON of data
