### ISSUE TITLE
Core i7 11700 has no temp-sensors

### ISSUE THREAD

**Issue by MDAPPDEV** [openhardwaremonitor/openhardwaremonitor#1427]
with above CPU the tool only shows load-values. CPU temperature is not being shown anymore. 
If further information or logs are needed, just raise a hand and tell me what information you need.

**Comment by MDAPPDEV** [comment]
[OpenHardwareMonitor.Report.txt](https://github.com/openhardwaremonitor/openhardwaremonitor/files/6382768/OpenHardwareMonitor.Report.txt)
attached logfile

**Comment by bsodmike** [comment]
I can confirm this, thanks @MDAPPDEV

**Comment by Cereal-Killa** [comment]
https://github.com/openhardwaremonitor/openhardwaremonitor/pull/1431

**Comment by MDAPPDEV** [comment]
> 
> 
> #1431

Temp OK now on 11th gen Intel!
