### ISSUE TITLE
Is this still maintained?

### ISSUE THREAD

**Issue by ckozler** [openhardwaremonitor/openhardwaremonitor#1454]
Subject

Person listed maintaining the project hasn't had any github activity at all, so just wondering

**Comment by PhyxionNL** [comment]
https://github.com/LibreHardwareMonitor/LibreHardwareMonitor

**Comment by ckozler** [comment]
Thanks! I am guessing the maintainer here doesn't even login anymore else I would expect him to close this repo and link off to libre. People are still actively opening tickets/issues here and request changes and forks
