### ISSUE TITLE
CPUID HWMonitor

### ISSUE THREAD

**Issue by canklot** [openhardwaremonitor/openhardwaremonitor#1476]
Does CPUID HWMonitor and OpenHardwareMonitor share the same code base? They look very similar.

**Comment by DarthDestroyer** [comment]
Nope, they dont!

The similar look is more or less identical, but that are both pretty normal lists with some icons and text.
Even Excel could look similar in a dozen clicks...

But the interesting thing is, OHM is open source and written in c#, all the other HW Tools are Closed and in other languages
