### ISSUE TITLE
Is this project still active?

### ISSUE THREAD

**Issue by Jibun-no-Kage** [openhardwaremonitor/openhardwaremonitor#1597]
Is this project still active?

**Comment by Mrnofish** [comment]
Development stopped at the end of 2020, as everybody can see.

@moellerm forked a project and pushed a commit in early 2023, so he seemingly survived COVID, but is no longer interested in OHM or just too busy to continue.

Pity, it used to be my favorite program of the kind.

**Comment by Jibun-no-Kage** [comment]
Yeah... hoped otherwise.  Interesting footnote... I was able to interface powershell to the 0.9.6 version of the DLL and it works, at least for what I need, to pull the CPU temperatures.  Guess I will look at LibreHardwareMonitor as well.
