### ISSUE TITLE
OHM keeps forgetting settings on multiple systems

### ISSUE THREAD

**Issue by GoogleCodeExporter** [openhardwaremonitor/openhardwaremonitor#501]
```
Open Hardware Monitor 0.6.0 (and 0.5.1) keeps forgetting settings with every 
Windows shutdown and system reboot, on multiple systems.  I had OHM installed 
on a heavily used Windows 7 x64 desktop system where I first observed this 
behavior, but now the same behavior is evident on a new install of Windows 7 on 
a laptop.  OHM forgets EVERYTHING: Options, gadget settings, modified device 
names, all of it.

I have attached files from both the desktop and laptop systems.

```

Original issue reported on code.google.com by `mark.a.c...@gmail.com` on 17 Aug 2013 at 10:16

Attachments:
- [OpenHardwareMonitor.Report (desktop).txt](https://storage.googleapis.com/google-code-attachments/open-hardware-monitor/issue-501/comment-0/OpenHardwareMonitor.Report %28desktop%29.txt)
- [OpenHardwareMonitor.Report (laptop).txt](https://storage.googleapis.com/google-code-attachments/open-hardware-monitor/issue-501/comment-0/OpenHardwareMonitor.Report %28laptop%29.txt)

**Comment by andysworkshop** [comment]
Confirmed fixed by me as well. I was fine with 0.6.0 on Windows 8.1 then it started to forget startup settings after the upgrade to Windows 10. 0.7.0 fixes the problems. On a side note - application settings should be stored in the per-user `%LOCALAPPDATA%` root location and not in the application installation directory.

**Comment by Hayk985** [comment]
Seems this issue is still actual
Windows 10.

**Comment by Richard127** [comment]
I'm getting this with latest version (0.9.5). I lose all the settings and the gadget disappears and has to be re configured.
