### ISSUE TITLE
GPU frequency plot show half values

### ISSUE THREAD

**Issue by GoogleCodeExporter** [openhardwaremonitor/openhardwaremonitor#701]
```
The gpu core frequency as read in the text output is 50, 405 and 920 MHz. This 
is verified in msi afterburner

When plotting the frequency, the plot displays values half of that.


OHM version 0.7.1 Beta, OS is windows 8.1 professional


```

Original issue reported on code.google.com by `aaabbbjj...@hotmail.com` on 22 May 2015 at 11:20

**Comment by moellerm** [comment]
This issue has been fixed with commit 5dfad04. An alpha version with the fix can be found here:

http://openhardwaremonitor.org/files/openhardwaremonitor-v0.7.1.1-alpha.zip
