### ISSUE TITLE
.exe.config and .config files

### ISSUE THREAD

**Issue by GoogleCodeExporter** [openhardwaremonitor/openhardwaremonitor#707]
```
What is the expected output? What do you see instead?
In program folder I have two config files: OpenHardwareMonitor.exe.config and 
OpenHardwareMonitor.config
It will be great if this will be one file.

What version of the product are you using? On what operating system?
0.7.1 Windows 8.1

Please provide any additional information below.


Please attach a Report created with "File / Save Report...".


```

Original issue reported on code.google.com by `TomZenk...@gmail.com` on 12 Jun 2015 at 9:26

**Comment by moellerm** [comment]
The OpenHardwareMonitor.exe.config file is required by Windows to be able to run the Open Hardware Monitor on older versions of the .NET framework (version 2.0).

OpenHardwareMonitor.config file contains the current user settings and recorded plot data. 

The two files can't really be merged.
