### ISSUE TITLE
Remember window layout

### ISSUE THREAD

**Issue by GoogleCodeExporter** [openhardwaremonitor/openhardwaremonitor#709]
```
This is a feature request.
Please could you implement a way for Open Hardware Monitor to remember how I 
set the window, so it is organised in the same way next time I load the app?

For instance, I collapse all but the temperature (clocks, loads, volts, etc.) 
when I'm using OHM, but when I re-open the app, they are expanded again.

Also, I have the graph at the bottom, and stretch it up to fill the space 
created after collapsing the above mentioned stats. I have to resize this every 
time too.

Kind Regards
```

Original issue reported on code.google.com by `standard...@gmail.com` on 16 Jun 2015 at 4:46

**Comment by maxim-boligatov** [comment]
Do you have any plans to implement it?

**Comment by jrmain** [comment]
I'd really like to see this fixed. Any chance it will happen?

**Comment by PamboHambo** [comment]
Just adding my +1 to this idea. Even if the window size/position isn't saved, the collapsed/expanded state of each sensor tree being saved would be very convenient.

**Comment by p1r473** [comment]
+1 here too. I always have to manually hide all the voltages (it doesn't remember my hides and collapses)

**Comment by moellerm** [comment]
The collapsed/expanded state is now restored to its previous state in OHM version 0.9.3.

**Comment by isillo** [comment]
+1

**Comment by jrmain** [comment]
Gave up waiting and switched to Libre Hardware Monitor.
