### ISSUE TITLE
Not detecting CPU and GPU fan speed.

### ISSUE THREAD

**Issue by GoogleCodeExporter** [openhardwaremonitor/openhardwaremonitor#715]
```
OpenHardwareMonitor NOT detecting Fan speed of my newly bought PC.

What version of the product are you using? 
* I'm using, 0.7.1 Beta.

On what operating system?
* Windows 7 Ultimate x64

Screenshot
http://s12.postimg.org/6ode9x34t/cpu.jpg


REPORT
http://s000.tinyupload.com/?file_id=20383200549618553652


```

Original issue reported on code.google.com by `joseph.o...@gmail.com` on 6 Jul 2015 at 1:49

**Comment by moellerm** [comment]
The GIGABYTE GA-F2A78M-HD2 seems to be using an ITE IT8620E super I/O chip (identified from photos). The report posted above is no longer available. 

The support for this chip is still missing in OHM. In issue #756 a report for the same chip can be found. The problem will be tracked in issue #756.
