### ISSUE TITLE
No cpu temp in OpenHardwareMonitor.dll, but OHM show cpu temp in application

### ISSUE THREAD

**Issue by GoogleCodeExporter** [openhardwaremonitor/openhardwaremonitor#730]
```
What is the expected output? What do you see instead?
when using the open hardware monitor dll in C# I expect to see a value in the 
CPU temperature. currently it is NAN. the open hardware application itself is 
showing temperatures. 


What version of the product are you using? On what operating system?
7.1 beta, Windows 7-64bit


Please provide any additional information below.
cpu is i7-4970k, mobo is gigabyte ga-z97x-gt


Please attach a Report created with "File / Save Report...".
I can't attach a file for some reason.
```

Original issue reported on code.google.com by `kombattr...@gmail.com` on 20 Aug 2015 at 11:19

**Comment by DarthDestroyer** [comment]
You have to go through SubHardware and Update it too! ;)

For i As Integer = 0 To cp.Hardware.Count() - 1
            Dim hardware = cp.Hardware(i)
            hardware.Update()

            Select Case hardware.HardwareType
                Case HardwareType.Mainboard
                    TextBox3.AppendText("Motherboard: " & hardware.Name & vbCrLf & vbCrLf)
                    For k = 0 To hardware.SubHardware.Count - 1
                        Dim subhardware = hardware.SubHardware(k)
                        subhardware.Update()
                        TextBox3.AppendText(subhardware.Name & vbCrLf & vbCrLf)
                        For j = 0 To subhardware.Sensors.Count - 1
                            Dim sensor = subhardware.Sensors(j)
                            Select (sensor.SensorType)
                                Case 0
                                    TextBox3.AppendText("Voltage: " & sensor.Name & " - " & sensor.Value & vbCrLf)
                                Case 1
                                    TextBox3.AppendText("Clock: " & sensor.Name & " - " & sensor.Value & vbCrLf)
                                Case 2
                                    TextBox3.AppendText("Temperature: " & sensor.Name & " - " & sensor.Value & vbCrLf)
                                Case 3
                                    TextBox3.AppendText("Load: " & sensor.Name & " - " & sensor.Value & vbCrLf)
                                Case 4
                                    TextBox3.AppendText("Fan Speed: " & sensor.Name & " - " & sensor.Value & vbCrLf)
                                Case 5
                                    TextBox3.AppendText("Flow: " & sensor.Name & " - " & sensor.Value & vbCrLf)
                                Case 6
                                    TextBox3.AppendText("Fan Control: " & sensor.Name & " - " & sensor.Value & vbCrLf)
                                Case 7
                                    TextBox3.AppendText("Level: " & sensor.Name & " - " & sensor.Value & vbCrLf)
                                Case 8
                                    TextBox3.AppendText("Factor: " & sensor.Name & " - " & sensor.Value & vbCrLf)
                                Case 9
                                    TextBox3.AppendText("Power: " & sensor.Name & " - " & sensor.Value & vbCrLf)
                                Case 10
                                    TextBox3.AppendText("Data: " & sensor.Name & " - " & sensor.Value & vbCrLf)
                                Case Else
                                    TextBox3.AppendText(sensor.SensorType & " - " & sensor.Name & " - " & sensor.Value & vbCrLf)
                            End Select
                        Next
                        TextBox3.AppendText(vbCrLf)
                    Next

End Select
