### ISSUE TITLE
OHM Gadget interferes with 7Sidebar (8GadgetPack)

### ISSUE THREAD

**Issue by WhAtEvErYoUmEaN** [openhardwaremonitor/openhardwaremonitor#734]
The OHM 'Gadget' is not able to be put into the Vista Sidebar (or the 7Sidebar Gadget which emulates this behavior).

**Comment by moellerm** [comment]
This is more or less by design. The OHM gadget is a standalone implementation of a vista like sidebar gadget and does not need any sidebar (emulation) as host.
