### ISSUE TITLE
Skylake temps are not supported.

### ISSUE THREAD

**Issue by repcakk** [openhardwaremonitor/openhardwaremonitor#736]
Skylake CPU temperatures are not supported in Open Hardware Monitor.

**Comment by beele** [comment]
I made a fork that fixes the skylake temps not being reported! 
I also opened a pull request to have that code merged

https://github.com/beele/openhardwaremonitor/commit/ba2e32242c1d78626acb356c5ba605aa08976753

**Comment by moellerm** [comment]
The skylake support has been merged into the latest source
