### ISSUE TITLE
Would be good if "Close" minimized window instead of quitting app

### ISSUE THREAD

**Issue by amrith** [openhardwaremonitor/openhardwaremonitor#740]
The main window on openhwmonitor has the "X" which currently causes a quit. It would be better, especially if logging or gadget are enabled, to minimize instead, or minimize to tray with an explicit Quit option.

**Comment by Optiligence** [comment]
`Options` → `Minimize On Close`?

**Comment by amrith** [comment]
Yes, got it. Thanks!
