### ISSUE TITLE
No Temp for AMD Radeon HD 6450

### ISSUE THREAD

**Issue by ZhuDaHai** [openhardwaremonitor/openhardwaremonitor#742]
Latest version of OHM shows no temperature (or any stats) for the AMD Radeon HD 6450.
Any ideas?

**Comment by moellerm** [comment]
This is most likely because the AMD driver does not support it. Some lower end cards do not expose any sensors in the ADL (AMD Display Library), or they just do not have any sensors. The OHM does not directly access the GPU hardware.
