### ISSUE TITLE
lastest commits broke Nuvoton NCT6791D support

### ISSUE THREAD

**Issue by nchapet** [openhardwaremonitor/openhardwaremonitor#747]
as seen on these screenshots : 

Version 0.7.1 Beta :

![capture](https://cloud.githubusercontent.com/assets/15987361/11347793/4654c3aa-9223-11e5-80c0-06acd96b3683.PNG)

and last sources compiled :

![capture](https://cloud.githubusercontent.com/assets/15987361/11347844/81bdeef8-9223-11e5-8959-b27937596fa2.PNG)

**Comment by moellerm** [comment]
Can you save and attach a report (File -> Save Report...) for the version compiled from the latest source?

**Comment by nchapet** [comment]
of course ! :-)

here it is.
[OpenHardwareMonitor.Report.txt](https://github.com/openhardwaremonitor/openhardwaremonitor/files/48869/OpenHardwareMonitor.Report.txt)

**Comment by nchapet** [comment]
and I want to ask , is there something to do for OHM continues to monitor certain values ​​after waking from sleep ? indeed on 0.7.1 , all values ​​of the chip Nuvoton NCT6791D are no longer monitored, at least until the reset of the software.

**Comment by moellerm** [comment]
I think the i/o space lock is enabled again after waking from sleep, so the lines 

https://github.com/openhardwaremonitor/openhardwaremonitor/blob/master/Hardware/LPC/LPCIO.cs#L264-L275

should be executed again after waking from sleep. I guess this state is not correctly restored by the waking from sleep function of Windows.

**Comment by moellerm** [comment]
Please use issue #733 for the problems when waking from sleep. The issue is currently not fixed in the source code.

**Comment by nchapet** [comment]
OK ! :-)
