### ISSUE TITLE
ghost sensors on Nuvoton NCT6791D

### ISSUE THREAD

**Issue by nchapet** [openhardwaremonitor/openhardwaremonitor#755]
is it possible to remove temperatures and fans sensors as pointed on this screen capture ?

they refer to anything on my system.

thanks !
![capture](https://cloud.githubusercontent.com/assets/15987361/11595409/bf2f324e-9aaf-11e5-825c-02372a841184.PNG)
[OpenHardwareMonitor.Report.txt](https://github.com/openhardwaremonitor/openhardwaremonitor/files/52268/OpenHardwareMonitor.Report.txt)

**Comment by moellerm** [comment]
One can create a mainboard specific configuration in the OHM code. But for that one needs to know which fans are really wired on the mainboard (and the label of the connector), how all the voltages are scaled and how the temperatures are used. 

The easier solution is to just hide the sensors you don't need (right click on sensor -> Hide).

**Comment by nchapet** [comment]
indeed I have seen after opening a ticket. I can possibly provide you this information if you wish , that of the Asus Z97I -PLUS I have.
