### ISSUE TITLE
Alert system

### ISSUE THREAD

**Issue by RiccardoB** [openhardwaremonitor/openhardwaremonitor#758]
It would be useful to have an alert system that permits to set min/max thresholds on every component and if a value goes over the limit do any (or all) of these alerts:
* write a log (one or more, selected folders, custom template)
* start a sound (select sound, sound the buzzer)
* send an email (one or more, cc or bcc, custom template)

*I've inserted possible advanced features in parenthesis*

**Comment by moellerm** [comment]
This has been suggest already in issue #35.
