### ISSUE TITLE
OpenHardware Monitor has Completely disappeared

### ISSUE THREAD

**Issue by hushpa** [openhardwaremonitor/openhardwaremonitor#774]
so I downloaded theOpenHardware Monitor   - easy - came right up -started playing a game and the computer locked up as expected - surprisingly it was not the cpu overheating  -

so I got the computer going again after a few tries and OpenHardware Monitor
has Completely disappeared - never saw that one before -

apparently I'm going to have to keep  downloading it  till I get this sorted out

:-?

apparently this guy has disappeared as well - at least as far as gmail is concerned
mmoeller@openhardwaremonitor.org.

**Comment by Slion** [comment]
So your computer crashes and you used OHM to check the CPU temperature could not be the issue right?

**Comment by hushpa** [comment]
had a virus - long gone now tks

**Comment by Slion** [comment]
Can you close the ticket then?
