### ISSUE TITLE
Is this still be supported?

### ISSUE THREAD

**Issue by antmck2016** [openhardwaremonitor/openhardwaremonitor#783]
It's 2 years since last update.  Is this still being supported or not anymore?

**Comment by Phyxion** [comment]
Would be nice if @moellerm added a few admins to at least merge the pull requests (if decent).

**Comment by DarthDestroyer** [comment]
Yep @Phyxion, that would be one Solution!
But i hope, that @moellerm would come back, too!

**Comment by SearchForTheCode** [comment]
Totally agree, would be a shame..

Besides some important stuff ist already there like the new skylake cpus LGA 1151 which it seems are not working.

**Comment by DarthDestroyer** [comment]
I'm new here at github... 
Is it not possible, that anyone fork it and we work together on extensions, so that @moellerm decide afterwards to implement that, when he cames back? 
I'm no Lawyer and i dont know if it is possible with the given License... But it will be the last Solution, when our @moellerm doesnt came back... 

I hope honestly, that everything is ok with @moellerm and he is only busy or not interested to improve this tool! 
Kind Regards!

**Comment by SearchForTheCode** [comment]
Of course its open source. Anyone can use this project, create a new one (under the given license). But those persons need the insight like @moellerm  in terms of documentations (intel, amd, the gpu manufacturers) so they can extend new stuff. It is of course not that "easy" if someone has never done stuff in this area. But it could be an option.

We all hope @moellerm  is fine as he has done great work by providing this monitor.

**Comment by DarthDestroyer** [comment]
When you look at the Pull Requests and the forks... there are people who know what they do... 

it begins with small extensions and end up at new hardware support! here are some great people with good knowledge... it would be great to stick them together ;-)

im working at voltage support for nvidia gpus at the moment...

**Comment by SearchForTheCode** [comment]
Great would be skylake support, as this is more and more becoming usual. But yeah you are absolutely right about the community (i did forget about the pull requests.)

**Comment by moellerm** [comment]
I'm fine and back for now. I have been lacking mostly time.

The latest alpha version 

http://openhardwaremonitor.org/files/openhardwaremonitor-v0.7.1.5-alpha.zip

should support all currently known Intel CPUs. If you have a CPU that is not supported, please create a new issue with an attached report.

**Comment by antmck2016** [comment]
Great to have you back.  Thanks for the update.

**Comment by Phyxion** [comment]
@moellerm Could you still add a few admins for pull requests, etc?

**Comment by SearchForTheCode** [comment]
Great to have you back.. Thats so true :) 

Generally, if you create an "guideline" or "workflow" for integrating new CPUs, i guess this would help a lot, so we can help you out more easily :)

**Comment by DarthDestroyer** [comment]
Nice to have you back! Wohooo!!!
