### ISSUE TITLE
Asus X99 - Wrong Temperatures

### ISSUE THREAD

**Issue by tinect** [openhardwaremonitor/openhardwaremonitor#784]
![unbenannt](https://cloud.githubusercontent.com/assets/135993/13117778/9a38bc62-d5a1-11e5-8adb-6fce254605cd.JPG)

Hey,
I'm using your lib, to add an automatically fan-control. But I'm having problems to read the temperature of mainboard-sensors. I saw that you tool cannot read the temperatures, too.
Is here any possibility to fix this?

On the left part of image you see the temperatures, right are the real ones (are same to asus-tool). I need the Temperature of the T-Sensor very important to do the work.

Thank you!!!!!!!

Best Regards,
Sebastian

**Comment by avtar** [comment]
I have an ASUS X99-Deluxe motherboard and I'm experiencing the same issue. Some motherboard sensor readings are showing temperatures of 100 C or more on an idle system whereas HWMonitor and the ASUS AI Suite report more reasonable temperatures hovering between 30 - 45 C.
