### ISSUE TITLE
Latest version of OHM

### ISSUE THREAD

**Issue by AZMikey2000** [openhardwaremonitor/openhardwaremonitor#803]
Hi,

I use a software update program (SUMo) and it reports that there's version v0.7.1.4 of OHM, but I don't know where to find it to download it.  Is SUMo misreporting that version?

Mike

**Comment by wingers999** [comment]
[http://openhardwaremonitor.org/files/openhardwaremonitor-v0.7.1.4-alpha.zip](url)

**Comment by antmck2016** [comment]
This link gives me a 404 error.

**Comment by moellerm** [comment]
The url above as text is correct, github just somehow failed to produce a correct link. Here is a working link:

http://openhardwaremonitor.org/files/openhardwaremonitor-v0.7.1.4-alpha.zip
