### ISSUE TITLE
Radeon RX480 Current Voltage is not shown

### ISSUE THREAD

**Issue by ischilling** [openhardwaremonitor/openhardwaremonitor#826]
This bug was 'worse' three Radeon driver versions ago, the current voltage wasn't shown at all. 

*Current status* is, that the voltage isn't shown occasionally, this is related to #825.

![2016-07-15 Radeon rx480 current voltage is not shown bug](https://cloud.githubusercontent.com/assets/658945/16871474/60f87338-4a87-11e6-8aa1-f49092ecea48.PNG)

**Comment by DarthDestroyer** [comment]
I would prefer, that you create ONE Issue about that... Only for handling!

**Comment by ischilling** [comment]
@DarthDestroyer from my point of view, #825 and #826 are two different bugs, from a developer standpoint I understand they might be fixed in one turn... So which one should I delete?

**Comment by DarthDestroyer** [comment]
Yeah... You got it ;-) but its not so bad! 

It doesnt matter, what one will stay... 

Regards

**Comment by ischilling** [comment]
On request of @DarthDestroyer #826 is herewith closed, #825 remains :+1:
