### ISSUE TITLE
Intel i5 6600K - Missing clocks and temps values

### ISSUE THREAD

**Issue by Hertizch** [openhardwaremonitor/openhardwaremonitor#839]
Using version 0.7.1.5 alpha

http://imgur.com/4Lyy1wE

http://imgur.com/wYxRc2G

**Comment by DarthDestroyer** [comment]
Hey,

You miss multiple Things at the Moment! Not only your CPU-Data!
Your MoBo isnt supported atm, too!

Btw. Screenshots doesnt help really! It would be better, if you post a Report!

Kind Regards

**Comment by Hertizch** [comment]
Haha, I did not even notice that. I was so focused on the CPU. I'll post my report tomorrow :]

**Comment by Hertizch** [comment]
Here is the report:
https://drive.google.com/open?id=0B5vPE3K0S33UUEFISjV5R1ZOOWM

**Comment by DarthDestroyer** [comment]
You got an error in your report! 

Could you try to run it as Administrator? 
That should fix the cpu Problem! 

But, you should open another Issue for your unsupported MoBo! 

Regards

**Comment by Hertizch** [comment]
Yes, it works now :)
