### ISSUE TITLE
reported as virus by Immunet

### ISSUE THREAD

**Issue by arnowi** [openhardwaremonitor/openhardwaremonitor#843]
Is anyone else having this problem?
As soon as I download the programme it is quarantined
![quarantined](https://cloud.githubusercontent.com/assets/13592761/17836331/b38f096c-678e-11e6-9fa2-d434d1addc78.png)

**Comment by DarthDestroyer** [comment]
First, make sure "where" you Download this from! 

Second, a False warning could be possible, because it sets some things up, that other (bad) tools used in the past! 

When you pay attention to Nr. 1, you are out of danger!

**Comment by arnowi** [comment]
Hello Daniel,


I got it from http://openhardwaremonitor.org/downloads/
Basically I just need to know if it's ok to mark it as safe. It didn't
happen before so it was suspicious to get these messages suddenly.

Thanks for the reply.


Best regards,
Arno

**Comment by DarthDestroyer** [comment]
Make sure, that your pc is clean and safe! 
There was a report, where someone had a similar Problem. He had a virus in the executable because it got infected. 

The Source and that URL should be safe! 
No one can safely say 100%, but you are not alone ;-)

Kind Regards

**Comment by akej74** [comment]
I can confirm that I get a similar problem when starting OpenHardwareMonitor downloaded here:
[http://openhardwaremonitor.org/files/openhardwaremonitor-v0.7.1.5-alpha.zip](url)

I'm using "Trend Micro" and I get the following warning:

**Malicious Behavior Detections**
Malware behaviour blocking, File System
Target: \Device\Harddsik0\DR0
Operation: Create

Maybe a false positive...?

**Comment by arnowi** [comment]
I'd marked it as safe and so far I've noticed no suspicious behaviour.
