### ISSUE TITLE
Tray Icon: Values on black task bar

### ISSUE THREAD

**Issue by jwhipp** [openhardwaremonitor/openhardwaremonitor#848]
The tray icon when set to display a value displays that value in black which makes it impossible to see on a taskbar with a black background.

Suggested Fix:

Either auto detect taskbar color if possible or allow the task bar font color to be adjustable.

**Comment by SoWhy** [comment]
Right-click icon and select "change color"?

**Comment by jwhipp** [comment]
Not sure why I didn't see that option.   That works, thanks!
