### ISSUE TITLE
Wrong chart values

### ISSUE THREAD

**Issue by mellamonick** [openhardwaremonitor/openhardwaremonitor#854]
The max value is 1595 but the chart shows 1000.

![captura](https://cloud.githubusercontent.com/assets/22411364/18807496/0160683c-8249-11e6-828d-d2de05ee5c22.JPG)

**Comment by moellerm** [comment]
The max value is the greatest value since you started the Open Hardware Monitor. The plot shows value for the last 24h (if OHM has been running). The latest ~4min are missing on your plot (change time axis), maybe the peak value occurred during that time.
