### ISSUE TITLE
Support for GEFORCE GTX 1070

### ISSUE THREAD

**Issue by ShamekindsMe** [openhardwaremonitor/openhardwaremonitor#856]
[OpenHardwareMonitor.Report.txt](https://github.com/openhardwaremonitor/openhardwaremonitor/files/499149/OpenHardwareMonitor.Report.txt)

Thank you +1:

**Comment by DarthDestroyer** [comment]
1. Use the latest Version => http://openhardwaremonitor.org/files/openhardwaremonitor-v0.7.1.5-alpha.zip

2. Make sure, you had run it as admin!

3. Have you installed the latest nvidia Drivers?

**Comment by ShamekindsMe** [comment]
Thank you for your super fast answer!  Here is a new report made with the latest version.
[OpenHardwareMonitor.Report.txt](https://github.com/openhardwaremonitor/openhardwaremonitor/files/499178/OpenHardwareMonitor.Report.txt)

I confirm that I have the latest Nvidia driver.  Also, the GPU sensors are not available via GPU-Z. Maybe it's a problem with my card.  I am accessing the machine via Remote Desktop, could it be the cause of the problem? Many thanks.
![capture](https://cloud.githubusercontent.com/assets/1037382/18931025/76c97fa8-8598-11e6-9fbf-12cac4afad16.PNG)

**Comment by DarthDestroyer** [comment]
Yes, RDP is something problematic at that - dont know exactly why...

Could you try it at local?

**Comment by ShamekindsMe** [comment]
Unfortunately, the machine is located in France and I’m in Quebec. :)  I will ask someone to test the machine for me tomorrow morning.  Thanks.

**Comment by ShamekindsMe** [comment]
Not working even locally.

**Comment by DarthDestroyer** [comment]
That is weird! GPUZ doesnt work, too?

**Comment by ShamekindsMe** [comment]
No.  I just have 2 sensors in GPU-Z and they both show 0.0MHZ.  Is the GTX 1070 is supposed to be supported?  If so, maybe I have a problem with my driver or my setup?  What do you think?

**Comment by DarthDestroyer** [comment]
i dont see a reason why it shouldnt be supported!

**Comment by moellerm** [comment]
Remote desktop does not work because the GPU driver is not loaded. Windows uses a "dummy" GPU driver that redirects the desktop to the remote system.

If it does not work locally (and neither does GPU-Z), try installing the latest drivers from NVIDIA and make sure the GTX 1070 is really active.

There are systems where OHM works fine with a GTX 1070, so this is most likely a driver/system configuration issue.
