### ISSUE TITLE
CPU Clocks and Temps not showing, i5-6600K

### ISSUE THREAD

**Issue by kaleeb42** [openhardwaremonitor/openhardwaremonitor#859]
Just downloaded this software as an alternative to CPUID HWMonitor but it's not registering my CPU clock speed or temps or fan speeds.

Gigabyte Z170-HD3-CF Motherboard

[OpenHardwareMonitor.Report.txt](https://github.com/openhardwaremonitor/openhardwaremonitor/files/499727/OpenHardwareMonitor.Report.txt)

**Comment by DarthDestroyer** [comment]
Your cpu is not supported,  yet! 

But you can Download a fork where the 6xxx architecture is already implemented! 

Your Mainboard isnt supported, too! but there are already issues for your Problems!

**Comment by kaleeb42** [comment]
The Alpha version works fine. Thanks for your help.
