### ISSUE TITLE
No sensors on ATI Gpu when connecting via RDP

### ISSUE THREAD

**Issue by ShamekindsMe** [openhardwaremonitor/openhardwaremonitor#862]
I am losing all the sensors when I connect to the machine via Remote Desktop.  Even after I have disconnected my session, I am still unable to see the sensors values.  However, I can get the sensors again by closing and restarting the app.  Same issue when I use the DLL in a c# project.

**Comment by moellerm** [comment]
The GPU is not active (and/or the GPU drivers are not loaded) when accessing a machine via remote desktop. I currently do not see a way to get any information from the GPU when using the remote desktop.

The Open Hardware Monitor enumerates hardware devices only while starting (or when using File -> Reset), so this is normal behavior.
