### ISSUE TITLE
ITE IT8733 chip.

### ISSUE THREAD

**Issue by T-Hacker** [openhardwaremonitor/openhardwaremonitor#863]
Hi, I'm working with a Gigabyte X99-Designare EX-CF motherboard, which uses an ITE IT8620E for the system fans, but an ITE IT8733 for the dual CPU fan headers. Currently, there is no support for the 8733.

Are you consider adding support for it?

**Comment by tds4u** [comment]
I would push my change but I can't: Error 403 :-/

Added IT8731F and IT8733F

**Comment by DarthDestroyer** [comment]
you should be able to push or link your fork?

GJ!

**Comment by tds4u** [comment]
I'm not having a fork, and pushing seems impossible:
```
git.exe push --progress "OpenHardwareMonitor" master:master

remote: Permission to openhardwaremonitor/openhardwaremonitor.git denied to tds4u.
fatal: unable to access 'https://github.com/openhardwaremonitor/openhardwaremonitor/': The requested URL returned error: 403

git did not exit cleanly (exit code 128) (2828 ms @ 05.10.2016 20:17:26)
```

**Comment by DarthDestroyer** [comment]
That is the Problem ;) you dont have the permission to post to ohwm master ;)

Create a Fork and push it to this! After that, you can create a Pull Request for ohwm master and everyone can see your addition in your fork / the pull request and @moellerm can accept these (then it is in the master!)
