### ISSUE TITLE
Total LBA written incorrect

### ISSUE THREAD

**Issue by skibbipl** [openhardwaremonitor/openhardwaremonitor#871]
I have Samsung 830 Pro SSD drive as a system drive. I've updated to latest OHM 0.8 and I can see new Total LBA Written sensor. It shows 322,8 GB, but its not correct. Samsung Magician shows 16.30 TB written to the disk so OHM definitely displays wrong value.
Is there anything I can do to help you debug and fix this issue?

**Comment by moellerm** [comment]
Please create a report file with the OHM (File -> Save Report...) and attach it here.
And also note the exact value from Samsung Magician at the same time.

**Comment by skibbipl** [comment]
OK, I think I know what's the issue. My samsung SSD device reports total writs like this (from OHM report):
`F1 Total LBA Written                  F52091290800 99    99    0     332.5353`
But the value is called total LBA not total bytes. My disk has following bytes per sector:
`Bytes Per Sector  :                512`
Basically total LBA != Total bytes written. I suppose OHM should use following formula to display written data:
` Total bytes written = Total LBA written * Bytes Per Sector`
Displaying LBA writes is misleading.

**Comment by azachert** [comment]
I will try to look at this tonight, as I was the last one messing with this code,

**Comment by moellerm** [comment]
I have it fixed almost, will commit it in a few minutes.

**Comment by moellerm** [comment]
I have tried to fix the issue in commit 336a4b5a0cb94dd5422d1815076ed72ff044c97d

You can find a new alpha version here: http://openhardwaremonitor.org/files/openhardwaremonitor-v0.8.0.1-alpha.zip

**Comment by skibbipl** [comment]
Looks OK. Thanks for improving this feature.
![obraz](https://cloud.githubusercontent.com/assets/4746858/20155311/9313b710-a6cb-11e6-9dc4-03c82c4c3352.png)

**Comment by moellerm** [comment]
Thx for testing
