### ISSUE TITLE
i don't get i7-6800k sensor values

### ISSUE THREAD

**Issue by indigo1715** [openhardwaremonitor/openhardwaremonitor#876]
i don't get cpu sensor values without cpu load values.

but different pc(i5-4690) can get all of cpu values(can get clocks,temperatures,load,powers).

this code build visual studio c# winform project added OpenHardwareMonitorLib.dll

  private void button1_Click(object sender, EventArgs e)
        {
            String temp = String.Empty;

            Computer c = new Computer()
            {
                CPUEnabled = true
            };

            c.Open();

            foreach (var hardware in c.Hardware)
            {
                if (hardware.HardwareType == HardwareType.CPU)
                {
                    hardware.Update();
                    foreach (var sensors in hardware.Sensors)
                    {
                        if (sensors.SensorType != SensorType.Level)
                            temp +=( sensors.Name + ": " + sensors.Value.GetValueOrDefault()+ "\r");
                    }
                }
            }
            MessageBox.Show(temp);
        }

but i did run openhardware.exe, all of cpu values is visible.

i don't understand why this problem.

please answer.

![bandicam 2016-11-19 16-24-16-898](https://cloud.githubusercontent.com/assets/23443730/20453835/e0e408fe-ae74-11e6-90d4-4e7d5947c466.jpg)

![bandicam 2016-11-19 16-24-30-557](https://cloud.githubusercontent.com/assets/23443730/20453836/e45098b8-ae74-11e6-9dd9-5e2599f404f5.jpg)

**Comment by moellerm** [comment]
The kernel driver did not get loaded. Make sure you run your application with admin rights and you include the app.manifest from the Source/Resources folder into your exe.
