### ISSUE TITLE
Missing Support: Z10A SLI Motherboard

### ISSUE THREAD

**Issue by GingaVytis** [openhardwaremonitor/openhardwaremonitor#886]
Name is detected properly but no other information is shown.
MSI Z170A SLI (MS-7998)
Attached report to post.
[OpenHardwareMonitor.Report(Z170A SLI).txt](https://github.com/openhardwaremonitor/openhardwaremonitor/files/641141/OpenHardwareMonitor.Report.Z170A.SLI.txt)

I'd love to help out and try and code this myself, although I'm a bit of an amateur. Is there any documentation or suggestions on how to get the motherboard sensor information?

**Comment by DarthDestroyer** [comment]
You could try => #884 ;)

**Comment by GingaVytis** [comment]
Awesome, got it working. Thanks so much! Next time I'll make sure to look around before I ask questions that have already been answered lul
