### ISSUE TITLE
Allow us to change the color of the graph plots

### ISSUE THREAD

**Issue by lavacano201014** [openhardwaremonitor/openhardwaremonitor#887]
Because all the temperatures plotted on my graph are in different shades of yellow. I need to change them or else the graph feature is useless for me.

**Comment by dwilhelm** [comment]
Which version are you using? The most recently released version (0.8.0) adds customizable pen colors, so you should be all set after upgrading.

**Comment by lavacano201014** [comment]
For some reason I thought this program had an automatic update handler, so I didn't think to upgrade first :V 

but yeah there it is
