### ISSUE TITLE
Restore tray icons after reboot

### ISSUE THREAD

**Issue by SoWhy** [openhardwaremonitor/openhardwaremonitor#896]
OS: Win7x64

I love OHM to quickly display CPU and GPU core temp in my taskbar but after every reboot the icons are gone and I have to select them anew (and change colors again as well). Could you add an option to restore tray icons on start?

**Comment by dwilhelm** [comment]
This works for me with these enabled:
Options > Start Minimized
Options > Minimize to Tray
Options > Run on Windows Startup

**Comment by dwilhelm** [comment]
Since the tray info is stored in OpenHardwareMonitor.config alongside the executable, maybe you're running it from a path where that file can't be saved?

**Comment by SoWhy** [comment]
Yeah, sorry, my bad. Shortly after posting this issue I noticed that v0.8.0 was up and now it works.
