### ISSUE TITLE
No 7700K temps

### ISSUE THREAD

**Issue by floxigen** [openhardwaremonitor/openhardwaremonitor#909]
temps of new intel i7 7700k kaby lake cpu won't display

http://imgur.com/HwZhTEk

**Comment by floxigen** [comment]
http://imgur.com/HwZhTEk

**Comment by DarthDestroyer** [comment]
Please post a Report!

**Comment by floxigen** [comment]
I don't really how to do this, i'm new on github

**Comment by DarthDestroyer** [comment]
Open the App, Top Left => File => Save Report...
Drag & Drop it into the Textfield here and its done ;)

**Comment by MrHugelberg** [comment]
I've got the same problem
I hope you don't mind that i post it here

[OpenHardwareMonitor.Report.txt](https://github.com/openhardwaremonitor/openhardwaremonitor/files/714089/OpenHardwareMonitor.Report.txt)

**Comment by floxigen** [comment]
I don't mind, thank you for that

**Comment by moellerm** [comment]
I have uploaded an alpha version with the issue fixed:

http://openhardwaremonitor.org/files/openhardwaremonitor-v0.8.0.2-alpha.zip

Please test and report the results here.

**Comment by MrHugelberg** [comment]
woah that was fast, tyvm!

now it works 👍 
[OpenHardwareMonitor.Report.txt](https://github.com/openhardwaremonitor/openhardwaremonitor/files/714802/OpenHardwareMonitor.Report.txt)

**Comment by jtugsop** [comment]
Moellerm's alpha fix works for me. I now have temps, power and clocks displaying for my 7700k.

**Comment by dreness** [comment]
Consider putting a link to the alpha with this fix on the download page :)

**Comment by eadmaster** [comment]
for some reason the CPU temperature reported does not match the one reported by the BIOS:
before booting Windows i've read 42°C in the BIOS, now OHM reports 30°C...
The voltages readings are also missing.
(I have a Pentium Kaby Lake G4560 with an ASRock B150M Pro4S/D3 motherboard)

**Comment by DarthDestroyer** [comment]
@eadmaster, please open an Issue for your Problem and add a Report please! You are wrong here! Sorry

**Comment by salighie** [comment]
Just as an FYI - I had the same issue with an i7-8700. v080-beta would only show core loads. No clocks, temps or powers... i can confirm that with v0802-alpha i get all that.

attaching reports for both versions in case it's helpful.
[OpenHardwareMonitor.Report_v080b.zip](https://github.com/openhardwaremonitor/openhardwaremonitor/files/1704217/OpenHardwareMonitor.Report_v080b.zip)
[OpenHardwareMonitor.Report_v0802a.zip](https://github.com/openhardwaremonitor/openhardwaremonitor/files/1704218/OpenHardwareMonitor.Report_v0802a.zip)

**Comment by JMM58** [comment]
I get almost all the important info from HardWarMonitor except the Vcore readings with my i5 8600K. I use the beta 0.8.0.3.
Motherboard is the Z370 Gigabyte Aorus Ultra Gaming Wifi.
Anybody some info about this issue?

**Comment by DarthDestroyer** [comment]
@JMM58 if you would add a Report here, i could lead you to the Solution! Z370 could be possible

**Comment by JMM58** [comment]
Report? Dou you mean printscreen? Sry but i'm a noob with this cases and english is not my native language.

**Comment by DarthDestroyer** [comment]
@JMM58, not my native language, too ;-)

You can create a Report in OHM with "File" - > Report - > Save

Something like that ;-)

**Comment by JMM58** [comment]
Sry but i don't know how to that. I will wait till the crew of OpenHardwareMonitor will resolve this issue.
Thx anyway for your aid.

**Comment by Whotakesmyname** [comment]
Encountered the same issue. Report attached. Thanks. @DarthDestroyer 
[OpenHardwareMonitor.Report.txt](https://github.com/openhardwaremonitor/openhardwaremonitor/files/3178421/OpenHardwareMonitor.Report.txt)

**Comment by DarthDestroyer** [comment]
@Whotakesmyname http://openhardwaremonitor.org/files/openhardwaremonitor-v0.8.0.3-alpha.zip

Could you try that and ensure you are starting as admin?

**Comment by JMM58** [comment]
I have for quite some time the v0.8.0.3 -alpha version but no V-core readings with my 8600K, also not as admin.

File report:
[OpenHardwareMonitor.Report.txt](https://github.com/openhardwaremonitor/openhardwaremonitor/files/3178584/OpenHardwareMonitor.Report.txt)

**Comment by DarthDestroyer** [comment]
@JMM58

Chip ID: Unknown ITE with ID 0x8686 at 0x2E/0x2F

i think that there is a solution for your chipset, probably in the Pull Requests

**Comment by Whotakesmyname** [comment]
> @Whotakesmyname http://openhardwaremonitor.org/files/openhardwaremonitor-v0.8.0.3-alpha.zip
> 
> Could you try that and ensure you are starting as admin?

Thanks for replying. I am sure it has been run as admin. On windows it cannot be started without admin, and if you don't manually do it, there will be a UAC message box, right? To make sure, I have also tried right click -> run as admin just now, and it appeared to be no different.

I have tried another tool, HWMonitor, and it works properly. Hope these information could help.

**Comment by Whotakesmyname** [comment]
> @Whotakesmyname http://openhardwaremonitor.org/files/openhardwaremonitor-v0.8.0.3-alpha.zip
> 
> Could you try that and ensure you are starting as admin?

Thanks very much. The alpha version works properly for me. Hope it could be merged into the next release soon.

**Comment by cnlohr** [comment]
@DarthDestroyer Even the alpha version you posted doesn't seem to work on my 9800X or any of my other Intel processors.  Any idea why processor temperature reading is so much rougher in OHW?
