### ISSUE TITLE
Kaby Lake 7700k incorrect clock speed

### ISSUE THREAD

**Issue by MrHugelberg** [openhardwaremonitor/openhardwaremonitor#911]
the core frequencys are shown up as 1300mhz
almost all the time

here's my report
[OpenHardwareMonitor.Report.txt](https://github.com/openhardwaremonitor/openhardwaremonitor/files/714976/OpenHardwareMonitor.Report.txt)

**Comment by Jacoozie** [comment]
Same here. 100% Cpu load, OpenHardwareMonitor shows 1300 MHz. In case of 0% load, the clocks are probably right.

**Comment by Jacoozie** [comment]
With the updated intelCpu.cs it works, thx a lot!

**Comment by moellerm** [comment]
I have uploaded a new alpha version with the patch from rmattuschka

http://openhardwaremonitor.org/files/openhardwaremonitor-v0.8.0.3-alpha.zip
