### ISSUE TITLE
[Enhancement] Web interface

### ISSUE THREAD

**Issue by RaydenX93** [openhardwaremonitor/openhardwaremonitor#941]
Hello, I've got an idea for OHM.
It would be nice if the program was able to create a web page, accessible via LAN, with all the stats the user chooses to display (temps or whatever). This way, the user would be able, for example, to check his hardware when using fullscreen applications via phone or tablet.

**Comment by DarthDestroyer** [comment]
its already implemented! 

start the webserver and have fun ;-)

**Comment by RaydenX93** [comment]
ok, so i guess i learnt a new thing xD
Sorry about this

**Comment by DarthDestroyer** [comment]
could you close your issue? 

Kind Regards
