### ISSUE TITLE
Mainboard msi h61m-p31/w8 can't get fan speed CPU

### ISSUE THREAD

**Issue by pkhdsth** [openhardwaremonitor/openhardwaremonitor#977]
Mainboard msi h61m-p31/w8 can't get fan speed CPU

**Comment by pkhdsth** [comment]
Mainboard msi h61m-p31/w8 can't get fan speed CPU g1630

**Comment by DarthDestroyer** [comment]
Please add a Report to your Issue!

**Comment by pkhdsth** [comment]
I'm sorry. Here is file log your Mainboard msi h61m-p31/w8 can't get fan speed CPU g1630.
[OpenHardwareMonitor.Report.txt](https://github.com/openhardwaremonitor/openhardwaremonitor/files/1034026/OpenHardwareMonitor.Report.txt)

**Comment by DarthDestroyer** [comment]
Chip ID: Unknown Winbond / Nuvoton / Fintek with ID 0x1106 at 0x4E/0x4F

**Comment by pkhdsth** [comment]
Chip ID: Unknown Winbond / Nuvoton / Fintek with ID 0x1106 at 0x4E/0x4F
Please, You can fix my problem? Thank you.
