### ISSUE TITLE
Show Plot(0.8.0 Beta) not draw anything on Windows [Version 10.0.15063, X64, I5]

### ISSUE THREAD

**Issue by alanackart** [openhardwaremonitor/openhardwaremonitor#980]
As the title has said, Show Plot show only this:

![capture](https://cloud.githubusercontent.com/assets/18682922/26281193/f8141ac6-3e22-11e7-80c3-640ced65ec6d.JPG)

**Comment by martynsmall** [comment]
Checkboxes appear next to each item in the main window when you open the plot.  These let you select which items to show, and without any ticked it will appear blank.

**Comment by alanackart** [comment]
thank for your replay, I have followed your instructions and indeed it works.
![capture](https://cloud.githubusercontent.com/assets/18682922/26299364/25889834-3f0d-11e7-8587-dcef02a0478b.JPG)

 I am sorry to bring you extra burden and I would be more careful to open an issue in Github.
