### ISSUE TITLE
ASUS CROSSHAIR VI HERO

### ISSUE THREAD

**Issue by mwebi** [openhardwaremonitor/openhardwaremonitor#993]
Hey,

the ASUS CROSSHAIR VI HERO is only displayed as a headline in OpenHardwareMonitor. Would it be possible to read the sensors (there's several like water pump RPM, water pump flow in/out, temp sensor etc?)

Website of mainboard: https://www.asus.com/us/Motherboards/ROG-CROSSHAIR-VI-HERO/

Thanks!

---------------------------------------

Mainboard

SMBIOS Version: 3.0

BIOS Vendor: American Megatrends Inc.
BIOS Version: 1201

System Manufacturer: System manufacturer
System Name: System Product Name
System Version: System Version

Mainboard Manufacturer: ASUSTeK COMPUTER INC.
Mainboard Name: CROSSHAIR VI HERO
Mainboard Version: Rev 1.xx

Processor Manufacturer: Advanced Micro Devices, Inc.
Processor Version: AMD Ryzen 7 1800X Eight-Core Processor
Processor Core Count: 8
Processor Core Enabled: 8
Processor Thread Count: 16
Processor External Clock: 100 Mhz

Memory Device [0] Manufacturer: Unknown
Memory Device [0] Part Number: Unknown
Memory Device [0] Device Locator: DIMM_A1
Memory Device [0] Bank Locator: Channel A
Memory Device [0] Speed: 0 MHz

Memory Device [1] Manufacturer: Unknown
Memory Device [1] Part Number: F4-3200C14-16GVK
Memory Device [1] Device Locator: DIMM_A2
Memory Device [1] Bank Locator: Channel A
Memory Device [1] Speed: 2400 MHz

Memory Device [2] Manufacturer: Unknown
Memory Device [2] Part Number: Unknown
Memory Device [2] Device Locator: DIMM_B1
Memory Device [2] Bank Locator: Channel B
Memory Device [2] Speed: 0 MHz

Memory Device [3] Manufacturer: Unknown
Memory Device [3] Part Number: F4-3200C14-16GVK
Memory Device [3] Device Locator: DIMM_B2
Memory Device [3] Bank Locator: Channel B
Memory Device [3] Speed: 2400 MHz

SMBIOS Table

 ABgAAAECAPAD/4Cciz8BAAAAAw0FDP//QW1lcmljYW4gTWVnYXRyZW5kcyBJbmMu
 ADEyMDEAMDUvMDkvMjAxNwAAARsBAAECAwTAoE/ENynnEZJjYEXLnusOBgUGU3lz
 dGVtIG1hbnVmYWN0dXJlcgBTeXN0ZW0gUHJvZHVjdCBOYW1lAFN5c3RlbSBWZXJz
 aW9uAFN5c3RlbSBTZXJpYWwgTnVtYmVyAFNLVQBUbyBiZSBmaWxsZWQgYnkgTy5F
 Lk0uAAACDwIAAQIDBAUJBgMACgBBU1VTVGVLIENPTVBVVEVSIElOQy4AQ1JPU1NI
 QUlSIFZJIEhFUk8AUmV2IDEueHgAMTcwNDk5NzcwNTAwMzExAERlZmF1bHQgc3Ry
 aW5nAERlZmF1bHQgc3RyaW5nAAADFgMAAQMCAwQDAwMDAAAAAAABAAMFRGVmYXVs
 dCBzdHJpbmcARGVmYXVsdCBzdHJpbmcARGVmYXVsdCBzdHJpbmcARGVmYXVsdCBz
 dHJpbmcARGVmYXVsdCBzdHJpbmcAAAgJBAABAAISEFVTQjNfMX40AFVTQjNfMX40
 AAAICQUAAQACEhBVU0IyXzExfjE0AFVTQjJfMTF+MTQAAAgJBgABAAISEFVTQjNf
 NX44AFVTQjNfNX44AAAICQcAAQACEhBVU0IzLjFfRUMyAFVTQjMuMV9FQzIAAAgJ
 CAABAAISEFVTQjMuMV9FQTMAVVNCMy4xX0VBMwAACAkJAAEAAgsfTEFOAExBTgAA
 CAkKAAEAAv8dQVVESU8AQVVESU8AAAgJCwABHwAAHUFBRlAAAAgJDAABEgAAEFVT
 QjE1MTYAAAgJDQABEgAAEFVTQjMuMV9FMQAACAkOAAESAAAQVVNCM185MTAAAAgJ
 DwAB/wAA/0NIQV9GQU4xAAAICRAAAf8AAP9DSEFfRkFOMgAACAkRAAH/AAD/Q0hB
 X0ZBTjMAAAgJEgAB/wAA/0NQVV9GQU4AAAgJEwAB/wAA/00uMihXSUZJKQAACAkU
 AAEiAAAgU0FUQTZHXzEyAAAICRUAASIAACBTQVRBNkdfMzQAAAgJFgABIgAAIFNB
 VEE2R181NgAACAkXAAEiAAAgU0FUQTZHXzc4AAAICRgAAf8AAP9UUE0AAAgJGQAB
 /wAA/1JPR19FWFQAAAgJGgAB/wAA/1RfU0VOU09SMQAACAkbAAH/AAD/V19QVU1Q
 AAAICRwAAf8AAP9SR0JfSEVBREVSAAAICR0AAf8AAP9GX1BBTkVMAAAICR4AAf8A
 AP9XX0ZMT1cAAAgJHwAB/wAA/1dfSU4AAAgJIAAB/wAA/1dfT1VUAAAICSEAAf8A
 AP9BSU9fUFVNUAAACAkiAAH/AAD/Q1BVX0ZBTgAACAkjAAH/AAD/Q1BVX09QVAAA
 CAkkAAH/AAD/Rl9QQU5FTAAACRElAAGlDQQEAAAMAQAAAAhKNkIyAAAJESYAAaUI
 BAMBAAwBAAAA40o2QjEAAAkRJwABpQgEAwIADAEAAADkSjZEMQAACgYoAIMBICAg
 VG8gQmUgRmlsbGVkIEJ5IE8uRS5NLgAACwUpAAREZWZhdWx0IHN0cmluZwBEZWZh
 dWx0IHN0cmluZwBBQk5FUgBEZWZhdWx0IHN0cmluZwAADAUqAAREZWZhdWx0IHN0
 cmluZwBEZWZhdWx0IHN0cmluZwBEZWZhdWx0IHN0cmluZwBEZWZhdWx0IHN0cmlu
 ZwAAIBQrAAAAAAAAAAAAAAAAAAAAAAAAACkLLAABgwEAAAAQIE9uYm9hcmQgSUdE
 AAApCy0AAYUBAAAAyCBPbmJvYXJkIExBTgAAKQsuAAGBAQAAA+IgT25ib2FyZCAx
 Mzk0AAASFy8AAwICAAAAAAAAAIAAAACAAAAAgAAAEBcwAAMDAwAAAAEvAAQAAAAA
 AAAAAAAAABMfMQAAAAAA////ATAA/wAAAAAAAAAAAAAAAAAAAAAAAAcTMgABiAEA
 AwADEAAQAAEGBQdMMSAtIENhY2hlAAAHEzMAAYkBABAAEBAAEAABBgUHTDIgLSBD
 YWNoZQAABxM0AAGKAQBAAEAQABAAAQYFCEwzIC0gQ2FjaGUAAAQwNQABA2sCEQ+A
 AP/7ixcDjmQABBCgD0ExMgAzADQABAUGCAgQBABrAAgACAAQAEFNNABBZHZhbmNl
 ZCBNaWNybyBEZXZpY2VzLCBJbmMuAEFNRCBSeXplbiA3IDE4MDBYIEVpZ2h0LUNv
 cmUgUHJvY2Vzc29yICAgICAgICAgAFVua25vd24AVW5rbm93bgBVbmtub3duAAAS
 FzYAAwICAAAAAAAAAIAAAACAAAAAgAAAESg3ADAANgD/////AAACAAECAgQAAAAD
 BAAFAAAAAAAAAAAAAAAAAERJTU1fQTEAQ2hhbm5lbCBBAFVua25vd24AVW5rbm93
 bgBVbmtub3duAAASFzgAAwICAAAAAAAAAIAAAACAAAAAgAAAESg5ADAAOABAAEAA
 AEAJAAECGoBAYAkDBAAFAgAAAACwBLAEsASwBERJTU1fQTIAQ2hhbm5lbCBBAFVu
 a25vd24AMDAwMDAwMDAARjQtMzIwMEMxNC0xNkdWSwAAFCM6AAAAAAD///8BOQAx
 AP///wAAAAAAAAAAAAAAAAAAAAAAABIXOwADAgIAAAAAAAAAgAAAAIAAAACAAAAR
 KDwAMAA7AP////8AAAIAAQICBAAAAAMEAAUAAAAAAAAAAAAAAAAARElNTV9CMQBD
 aGFubmVsIEIAVW5rbm93bgBVbmtub3duAFVua25vd24AABIXPQADAgIAAAAAAAAA
 gAAAAIAAAACAAAARKD4AMAA9AEAAQAAAQAkAAQIagEBgCQMEAAUCAAAAALAEsASw
 BLAERElNTV9CMgBDaGFubmVsIEIAVW5rbm93bgAwMDAwMDAwMABGNC0zMjAwQzE0
 LTE2R1ZLAAAUIz8AAAAAAP///wE+ADEA////AAAAAAAAAAAAAAAAAAAAAAAADRZA
 AAgAAAAAAAAAAAAAAAAAAAAAAWVufFVTfGlzbzg4NTktMQBmcnxGUnxpc284ODU5
 LTEAemh8Q058dW5pY29kZQAAfwRBAAAA

LPCIO

Chip ID: Unknown ITE with ID 0x8665 at 0x2E/0x2F

**Comment by DarthDestroyer** [comment]
Your Mainboard isnt supported, at the moment! 

It would help, if you could upload a full report!
Thanks and Regards

**Comment by mwebi** [comment]
Sure thing:

[OpenHardwareMonitor.Report.txt](https://github.com/openhardwaremonitor/openhardwaremonitor/files/1092140/OpenHardwareMonitor.Report.txt)

**Comment by BennehBoy** [comment]
There's a WIP branch here that adds preliminary support for the IT8665 -> https://github.com/azuisleet/openhardwaremonitor/commit/d4b763c01625d595e22b2b658e55696827b44dac#commitcomment-23040901

**Comment by moellerm** [comment]
The ITE super I/O chip IT8665E used on this mainboard should be supported in Open Hardware Monitor Version 0.9.2.
